export const EFFECT_TYPES = {
  DAMAGE_MODIFIER: "DAMAGE_MODIFIER",
  APPLY_CONDITION: "APPLY_CONDITION",
  REMOVE_CONDITION: "REMOVE_CONDITION",
  ENERGY_GAIN: "ENERGY_GAIN",
  ENERGY_REMOVE: "ENERGY_REMOVE",
  FORCE_RETREAT: "FORCE_RETREAT",
  DAMAGE_REDIRECT: "DAMAGE_REDIRECT",
  IMMUNITY: "IMMUNITY",
  BLOCK_ACTION: "BLOCK_ACTION",
  REVIVE: "REVIVE",
  TRANSFORM: "TRANSFORM",
  COPY_ITEM: "COPY_ITEM",
  DAMAGE: "DAMAGE",
  DAMAGE_FIXED: "DAMAGE_FIXED",
  DAMAGE_BY_FORMULA: "DAMAGE_BY_FORMULA",
  DAMAGE_RANDOM_TARGETS: "DAMAGE_RANDOM_TARGETS",
  DAMAGE_ANY_TARGET: "DAMAGE_ANY_TARGET",
  DAMAGE_ACTIVE_AND_BENCH: "DAMAGE_ACTIVE_AND_BENCH",
  DAMAGE_ALL_OPPONENT_BENCH: "DAMAGE_ALL_OPPONENT_BENCH",
  DAMAGE_SELF: "DAMAGE_SELF",
  DAMAGE_EXTRA_BY_ENERGY: "DAMAGE_EXTRA_BY_ENERGY",
  DAMAGE_EXTRA_BY_BENCH_CARD: "DAMAGE_EXTRA_BY_BENCH_CARD",
  DAMAGE_EXTRA_BY_TARGET_TYPE: "DAMAGE_EXTRA_BY_TARGET_TYPE",
  DAMAGE_EXTRA_BY_DICE: "DAMAGE_EXTRA_BY_DICE",
  DAMAGE_EXTRA_BY_COIN: "DAMAGE_EXTRA_BY_COIN",
  DAMAGE_CONSECUTIVE_STACK: "DAMAGE_CONSECUTIVE_STACK",
  DAMAGE_SPLIT: "DAMAGE_SPLIT",
  DAMAGE_TO_PREVIOUSLY_DAMAGED_BENCH: "DAMAGE_TO_PREVIOUSLY_DAMAGED_BENCH",
  HEAL: "HEAL",
  HEAL_SELF: "HEAL_SELF",
  HEAL_ACTIVE: "HEAL_ACTIVE",
  HEAL_BENCH: "HEAL_BENCH",
  HEAL_BENCH_CARD: "HEAL_BENCH_CARD",
  HEAL_ANY_SELF_CARD: "HEAL_ANY_SELF_CARD",
  HEAL_ANY_ALLY: "HEAL_ANY_ALLY",
  HEAL_EQUIPPED_CARD: "HEAL_EQUIPPED_CARD",
  HEAL_BY_DAMAGE_DEALT: "HEAL_BY_DAMAGE_DEALT",
  HEAL_ON_ENERGY_ATTACH: "HEAL_ON_ENERGY_ATTACH",
  HEAL_ALLY_ON_DAMAGE: "HEAL_ALLY_ON_DAMAGE",
  HEAL_PER_TURN: "HEAL_PER_TURN",
  HEAL_BENCH_GROUP: "HEAL_BENCH_GROUP",
  GAIN_HP_FROM_KO: "GAIN_HP_FROM_KO",
  ADD_ENERGY: "ADD_ENERGY",
  ADD_ENERGY_TYPED: "ADD_ENERGY_TYPED",
  ADD_TYPED_ENERGY: "ADD_TYPED_ENERGY",
  ADD_ENERGY_TO_TARGET: "ADD_ENERGY_TO_TARGET",
  ADD_ENERGY_TO_ACTIVE: "ADD_ENERGY_TO_ACTIVE",
  ADD_ENERGY_TO_BENCH: "ADD_ENERGY_TO_BENCH",
  ADD_ENERGY_BY_COIN: "ADD_ENERGY_BY_COIN",
  ADD_ENERGY_BY_DAMAGE_TAKEN: "ADD_ENERGY_BY_DAMAGE_TAKEN",
  ADD_ENERGY_ON_ATTACK: "ADD_ENERGY_ON_ATTACK",
  ADD_MULTIPLE_ENERGY: "ADD_MULTIPLE_ENERGY",
  REMOVE_ENERGY: "REMOVE_ENERGY",
  REMOVE_RANDOM_ENERGY: "REMOVE_RANDOM_ENERGY",
  MOVE_ENERGY: "MOVE_ENERGY",
  MOVE_ALL_BENCH_ENERGY_TO_ACTIVE: "MOVE_ALL_BENCH_ENERGY_TO_ACTIVE",
  MOVE_ALL_ENERGY_FROM_BENCH_TO_ACTIVE: "MOVE_ALL_ENERGY_FROM_BENCH_TO_ACTIVE",
  DISCARD_OWN_ENERGY: "DISCARD_OWN_ENERGY",
  ALLOW_ANY_ENERGY_TYPE: "ALLOW_ANY_ENERGY_TYPE",
  ENERGY_ANY_TYPE: "ENERGY_ANY_TYPE",
  ENERGY_COST_REDUCTION: "ENERGY_COST_REDUCTION",
  ENERGY_REQUIRED_TYPE: "ENERGY_REQUIRED_TYPE",
  DRAW_CARD: "DRAW_CARD",
  DRAW_MULTIPLE: "DRAW_MULTIPLE",
  SEARCH_RANDOM_BASIC: "SEARCH_RANDOM_BASIC",
  LOOK_TOP_DECK: "LOOK_TOP_DECK",
  REVEAL_OPPONENT_HAND: "REVEAL_OPPONENT_HAND",
  REVEAL_ONE_CARD: "REVEAL_ONE_CARD",
  SHUFFLE_OPPONENT_HAND: "SHUFFLE_OPPONENT_HAND",
  OPPONENT_DRAWS_LIMITED: "OPPONENT_DRAWS_LIMITED",
  OPPONENT_DRAWS_RANDOM: "OPPONENT_DRAWS_RANDOM",
  SWAP_HAND_CARD_RANDOM: "SWAP_HAND_CARD_RANDOM",
  FORCE_OPPONENT_SWAP_CARD: "FORCE_OPPONENT_SWAP_CARD",
  RETURN_CARD_TO_DECK: "RETURN_CARD_TO_DECK",
  RESURRECT_TO_DECK: "RESURRECT_TO_DECK",
  RESURRECT_FROM_DISCARD: "RESURRECT_FROM_DISCARD",
  REVEAL_ONE_OPPONENT_CARD: "REVEAL_ONE_OPPONENT_CARD",
  DISCARD_CARD: "DISCARD_CARD",
  SWITCH_ACTIVE: "SWITCH_ACTIVE",
  SWITCH_OWN_ACTIVE: "SWITCH_OWN_ACTIVE",
  SWITCH_OPPONENT_ACTIVE: "SWITCH_OPPONENT_ACTIVE",
  FORCE_SWITCH_OPPONENT_ACTIVE: "FORCE_SWITCH_OPPONENT_ACTIVE",
  OPPONENT_CHOOSES_NEW_ACTIVE: "OPPONENT_CHOOSES_NEW_ACTIVE",
  IGNORE_RETREAT_COST: "IGNORE_RETREAT_COST",
  REDUCE_RETREAT_COST: "REDUCE_RETREAT_COST",
  BLOCK_RETREAT: "BLOCK_RETREAT",
  ATTACK_FROM_BENCH: "ATTACK_FROM_BENCH",
  PROMOTE_FROM_BENCH: "PROMOTE_FROM_BENCH",
  SUMMON_FROM_BENCH: "SUMMON_FROM_BENCH",
  RESCUE_ACTIVE: "RESCUE_ACTIVE",
  APPLY_POISON: "APPLY_POISON",
  APPLY_BURN: "APPLY_BURN",
  APPLY_FREEZE: "APPLY_FREEZE",
  APPLY_PARALYSIS: "APPLY_PARALYSIS",
  APPLY_CONFUSE: "APPLY_CONFUSE",
  APPLY_SLEEP: "APPLY_SLEEP",
  REMOVE_CONDITIONS: "REMOVE_CONDITIONS",
  BURN: "BURN",
  PARALYZE: "PARALYZE",
  FREEZE: "FREEZE",
  CONFUSE: "CONFUSE",
  PREVENT_ATTACK: "PREVENT_ATTACK",
  PREVENT_RETREAT: "PREVENT_RETREAT",
  SKIP_NEXT_ATTACK: "SKIP_NEXT_ATTACK",
  CANNOT_USE_SAME_ATTACK_NEXT_TURN: "CANNOT_USE_SAME_ATTACK_NEXT_TURN",
  BUFF_DAMAGE: "BUFF_DAMAGE",
  BUFF_DAMAGE_THIS_TURN: "BUFF_DAMAGE_THIS_TURN",
  BUFF_DAMAGE_NEXT_TURN: "BUFF_DAMAGE_NEXT_TURN",
  BUFF_EQUIPPED_CARD_DAMAGE: "BUFF_EQUIPPED_CARD_DAMAGE",
  BUFF_DAMAGE_BY_TAG: "BUFF_DAMAGE_BY_TAG",
  BUFF_DAMAGE_BY_ATTACHED_ENERGY: "BUFF_DAMAGE_BY_ATTACHED_ENERGY",
  BUFF_BASE_ATTRIBUTES: "BUFF_BASE_ATTRIBUTES",
  INCREASE_MAX_HP: "INCREASE_MAX_HP",
  BUFF_HEAL_AMOUNT: "BUFF_HEAL_AMOUNT",
  DOUBLE_DAMAGE_AGAINST_TYPE: "DOUBLE_DAMAGE_AGAINST_TYPE",
  WEAKNESS_OVERRIDE: "WEAKNESS_OVERRIDE",
  ALPHA_POINT_OVERRIDE: "ALPHA_POINT_OVERRIDE",
  REDUCE_DAMAGE: "REDUCE_DAMAGE",
  REDUCE_NEXT_DAMAGE: "REDUCE_NEXT_DAMAGE",
  PREVENT_DAMAGE: "PREVENT_DAMAGE",
  PREVENT_DAMAGE_TYPE: "PREVENT_DAMAGE_TYPE",
  IMMUNE_TO_DAMAGE_TYPE: "IMMUNE_TO_DAMAGE_TYPE",
  IMMUNE_TO_NEGATIVE_EFFECTS: "IMMUNE_TO_NEGATIVE_EFFECTS",
  IGNORE_TOOL_EFFECTS: "IGNORE_TOOL_EFFECTS",
  HALVE_DAMAGE_TAKEN: "HALVE_DAMAGE_TAKEN",
  REFLECT_DAMAGE: "REFLECT_DAMAGE",
  REFLECT_DAMAGE_DOUBLED: "REFLECT_DAMAGE_DOUBLED",
  REFLECT_DOUBLE_DAMAGE: "REFLECT_DOUBLE_DAMAGE",
  REFLECT_HALVED_SHARED: "REFLECT_HALVED_SHARED",
  REDIRECT_DAMAGE: "REDIRECT_DAMAGE",
  REDIRECT_DAMAGE_TO_BENCH: "REDIRECT_DAMAGE_TO_BENCH",
  SHARE_DAMAGE: "SHARE_DAMAGE",
  TAKE_DAMAGE_INSTEAD: "TAKE_DAMAGE_INSTEAD",
  COIN_FLIP: "COIN_FLIP",
  DICE_ROLL: "DICE_ROLL",
  IF_DICE_GREATER_THAN: "IF_DICE_GREATER_THAN",
  IF_DICE_LESS_THAN: "IF_DICE_LESS_THAN",
  IF_TARGET_NATURE: "IF_TARGET_NATURE",
  IF_TARGET_TAG: "IF_TARGET_TAG",
  IF_SELF_HAS_ENERGY_COUNT: "IF_SELF_HAS_ENERGY_COUNT",
  IF_BENCH_HAS_CARD: "IF_BENCH_HAS_CARD",
  IF_BENCH_COUNT_BY_NATURE: "IF_BENCH_COUNT_BY_NATURE",
  IF_HAS_TOOL_ATTACHED: "IF_HAS_TOOL_ATTACHED",
  IF_CARD_WAS_ATTACKED: "IF_CARD_WAS_ATTACKED",
  IF_CARD_KNOCKED_OUT: "IF_CARD_KNOCKED_OUT",
  ON_ATTACK: "ON_ATTACK",
  ON_DAMAGE_TAKEN: "ON_DAMAGE_TAKEN",
  ON_ENERGY_ATTACHED: "ON_ENERGY_ATTACHED",
  ON_KNOCKOUT: "ON_KNOCKOUT",
  ON_TURN_START: "ON_TURN_START",
  ON_TURN_END: "ON_TURN_END",
  COPY_OPPONENT_ITEM: "COPY_OPPONENT_ITEM",
  TRANSFORM_INTO_BENCH_CARD: "TRANSFORM_INTO_BENCH_CARD",
  TRANSFORM_INTO_OPPONENT_BENCH_CARD: "TRANSFORM_INTO_OPPONENT_BENCH_CARD",
  ABSORB_OWN_BENCH_CARD: "ABSORB_OWN_BENCH_CARD",
  CREATE_TEMPORARY_UNIT: "CREATE_TEMPORARY_UNIT",
  PLAY_ITEM_AS_UNIT: "PLAY_ITEM_AS_UNIT",
  POISON: "POISON",
  DAMAGE_OVER_TIME: "DAMAGE_OVER_TIME",
  INSTANT_KNOCKOUT_IF_DAMAGE_TYPE: "INSTANT_KNOCKOUT_IF_DAMAGE_TYPE",
  COUNTER_DAMAGE: "COUNTER_DAMAGE",
  CANCEL_KNOCKOUT: "CANCEL_KNOCKOUT",
  RETURN_TO_HAND_ON_KO: "RETURN_TO_HAND_ON_KO",
  RETURN_TO_DECK_ON_KO: "RETURN_TO_DECK_ON_KO",
  RETURN_KNOCKED_OUT_TO_HAND: "RETURN_KNOCKED_OUT_TO_HAND",
  PREVENT_POINT_GAIN: "PREVENT_POINT_GAIN",
  CANCEL_KNOCKOUT_POINT: "CANCEL_KNOCKOUT_POINT",
  SEARCH_CARD_BY_FILTER: "SEARCH_CARD_BY_FILTER",
  STATUS_ON_ATTACKER: "STATUS_ON_ATTACKER",
  DISCARD_EQUIPMENT_AFTER_TRIGGER: "DISCARD_EQUIPMENT_AFTER_TRIGGER",
  DISABLE_SAME_ATTACK_NEXT_TURN: "DISABLE_SAME_ATTACK_NEXT_TURN",
};

const labelFromValue = value => value
  .split("_")
  .map(word => word.charAt(0) + word.slice(1).toLowerCase())
  .join(" ");

export const EFFECT_TYPE_LABELS = {
  [EFFECT_TYPES.DAMAGE_MODIFIER]: "Modificar dano",
  [EFFECT_TYPES.APPLY_CONDITION]: "Aplicar condicao",
  [EFFECT_TYPES.REMOVE_CONDITION]: "Remover condicao",
  [EFFECT_TYPES.ENERGY_GAIN]: "Ganhar energia",
  [EFFECT_TYPES.ENERGY_REMOVE]: "Remover energia",
  [EFFECT_TYPES.FORCE_RETREAT]: "Forcar recuo",
  [EFFECT_TYPES.DAMAGE_REDIRECT]: "Redirecionar dano",
  [EFFECT_TYPES.IMMUNITY]: "Imunidade",
  [EFFECT_TYPES.BLOCK_ACTION]: "Bloquear acao",
  [EFFECT_TYPES.REVIVE]: "Reviver carta",
  [EFFECT_TYPES.TRANSFORM]: "Transformar",
  [EFFECT_TYPES.COPY_ITEM]: "Copiar item",
  [EFFECT_TYPES.DAMAGE]: "Dano",
  [EFFECT_TYPES.DAMAGE_FIXED]: "Dano fixo",
  [EFFECT_TYPES.DAMAGE_BY_FORMULA]: "Dano por formula",
  [EFFECT_TYPES.DAMAGE_RANDOM_TARGETS]: "Dano em alvo aleatorio",
  [EFFECT_TYPES.DAMAGE_ANY_TARGET]: "Dano em qualquer alvo",
  [EFFECT_TYPES.DAMAGE_ACTIVE_AND_BENCH]: "Dano na ativa e banco",
  [EFFECT_TYPES.DAMAGE_ALL_OPPONENT_BENCH]: "Dano em todo banco oponente",
  [EFFECT_TYPES.DAMAGE_SELF]: "Dano em si mesmo",
  [EFFECT_TYPES.DAMAGE_EXTRA_BY_ENERGY]: "Dano extra por energia",
  [EFFECT_TYPES.DAMAGE_EXTRA_BY_BENCH_CARD]: "Dano extra por carta no banco",
  [EFFECT_TYPES.DAMAGE_EXTRA_BY_TARGET_TYPE]: "Dano extra por tipo do alvo",
  [EFFECT_TYPES.DAMAGE_EXTRA_BY_DICE]: "Dano extra por dado",
  [EFFECT_TYPES.DAMAGE_EXTRA_BY_COIN]: "Dano extra por moeda",
  [EFFECT_TYPES.DAMAGE_CONSECUTIVE_STACK]: "Dano acumulado consecutivo",
  [EFFECT_TYPES.DAMAGE_SPLIT]: "Dano dividido",
  [EFFECT_TYPES.DAMAGE_TO_PREVIOUSLY_DAMAGED_BENCH]: "Dano no banco ja ferido",
  [EFFECT_TYPES.HEAL]: "Cura",
  [EFFECT_TYPES.HEAL_SELF]: "Curar a si mesmo",
  [EFFECT_TYPES.HEAL_ACTIVE]: "Curar ativa",
  [EFFECT_TYPES.HEAL_BENCH]: "Curar banco",
  [EFFECT_TYPES.HEAL_BENCH_CARD]: "Curar carta do banco",
  [EFFECT_TYPES.HEAL_ANY_SELF_CARD]: "Curar qualquer carta propria",
  [EFFECT_TYPES.HEAL_ANY_ALLY]: "Curar qualquer aliada",
  [EFFECT_TYPES.HEAL_EQUIPPED_CARD]: "Curar carta equipada",
  [EFFECT_TYPES.HEAL_BY_DAMAGE_DEALT]: "Curar pelo dano causado",
  [EFFECT_TYPES.HEAL_ON_ENERGY_ATTACH]: "Curar ao anexar energia",
  [EFFECT_TYPES.HEAL_ALLY_ON_DAMAGE]: "Curar aliado ao causar dano",
  [EFFECT_TYPES.HEAL_PER_TURN]: "Cura por turno",
  [EFFECT_TYPES.HEAL_BENCH_GROUP]: "Curar grupo do banco",
  [EFFECT_TYPES.GAIN_HP_FROM_KO]: "Ganhar HP por nocaute",
  [EFFECT_TYPES.ADD_ENERGY]: "Adicionar energia",
  [EFFECT_TYPES.ADD_ENERGY_TYPED]: "Adicionar energia tipada",
  [EFFECT_TYPES.ADD_TYPED_ENERGY]: "Adicionar energia tipada",
  [EFFECT_TYPES.ADD_ENERGY_TO_TARGET]: "Adicionar energia ao alvo",
  [EFFECT_TYPES.ADD_ENERGY_TO_ACTIVE]: "Adicionar energia na ativa",
  [EFFECT_TYPES.ADD_ENERGY_TO_BENCH]: "Adicionar energia no banco",
  [EFFECT_TYPES.ADD_ENERGY_BY_COIN]: "Adicionar energia por moeda",
  [EFFECT_TYPES.ADD_ENERGY_BY_DAMAGE_TAKEN]: "Adicionar energia por dano recebido",
  [EFFECT_TYPES.ADD_ENERGY_ON_ATTACK]: "Adicionar energia ao atacar",
  [EFFECT_TYPES.ADD_MULTIPLE_ENERGY]: "Adicionar multiplas energias",
  [EFFECT_TYPES.REMOVE_ENERGY]: "Remover energia",
  [EFFECT_TYPES.REMOVE_RANDOM_ENERGY]: "Remover energia aleatoria",
  [EFFECT_TYPES.MOVE_ENERGY]: "Mover energia",
  [EFFECT_TYPES.MOVE_ALL_BENCH_ENERGY_TO_ACTIVE]: "Mover energias do banco para ativa",
  [EFFECT_TYPES.MOVE_ALL_ENERGY_FROM_BENCH_TO_ACTIVE]: "Mover energias do banco para ativa",
  [EFFECT_TYPES.DISCARD_OWN_ENERGY]: "Descartar propria energia",
  [EFFECT_TYPES.ENERGY_ANY_TYPE]: "Energia de qualquer tipo",
  [EFFECT_TYPES.ALLOW_ANY_ENERGY_TYPE]: "Permitir qualquer energia",
  [EFFECT_TYPES.ENERGY_COST_REDUCTION]: "Reduzir custo de energia",
  [EFFECT_TYPES.ENERGY_REQUIRED_TYPE]: "Exigir tipo de energia",
  [EFFECT_TYPES.DRAW_CARD]: "Comprar carta",
  [EFFECT_TYPES.DRAW_MULTIPLE]: "Comprar varias cartas",
  [EFFECT_TYPES.SEARCH_RANDOM_BASIC]: "Buscar basica aleatoria",
  [EFFECT_TYPES.LOOK_TOP_DECK]: "Ver topo do deck",
  [EFFECT_TYPES.REVEAL_OPPONENT_HAND]: "Revelar mao do oponente",
  [EFFECT_TYPES.REVEAL_ONE_CARD]: "Revelar uma carta",
  [EFFECT_TYPES.SHUFFLE_OPPONENT_HAND]: "Embaralhar mao do oponente",
  [EFFECT_TYPES.OPPONENT_DRAWS_RANDOM]: "Oponente compra aleatoria",
  [EFFECT_TYPES.OPPONENT_DRAWS_LIMITED]: "Oponente compra limitada",
  [EFFECT_TYPES.SWAP_HAND_CARD_RANDOM]: "Trocar carta da mao aleatoria",
  [EFFECT_TYPES.FORCE_OPPONENT_SWAP_CARD]: "Forcar oponente a trocar carta",
  [EFFECT_TYPES.RETURN_CARD_TO_DECK]: "Retornar carta ao deck",
  [EFFECT_TYPES.RESURRECT_TO_DECK]: "Ressuscitar para o deck",
  [EFFECT_TYPES.RESURRECT_FROM_DISCARD]: "Ressuscitar do cemiterio",
  [EFFECT_TYPES.REVEAL_ONE_OPPONENT_CARD]: "Revelar uma carta oponente",
  [EFFECT_TYPES.DISCARD_CARD]: "Descartar carta",
  [EFFECT_TYPES.SWITCH_ACTIVE]: "Trocar ativa",
  [EFFECT_TYPES.SWITCH_OWN_ACTIVE]: "Trocar sua ativa",
  [EFFECT_TYPES.SWITCH_OPPONENT_ACTIVE]: "Trocar ativa oponente",
  [EFFECT_TYPES.FORCE_SWITCH_OPPONENT_ACTIVE]: "Forcar troca do oponente",
  [EFFECT_TYPES.OPPONENT_CHOOSES_NEW_ACTIVE]: "Oponente escolhe nova ativa",
  [EFFECT_TYPES.IGNORE_RETREAT_COST]: "Ignorar custo de recuo",
  [EFFECT_TYPES.REDUCE_RETREAT_COST]: "Reduzir custo de recuo",
  [EFFECT_TYPES.BLOCK_RETREAT]: "Bloquear recuo",
  [EFFECT_TYPES.ATTACK_FROM_BENCH]: "Atacar do banco",
  [EFFECT_TYPES.PROMOTE_FROM_BENCH]: "Promover do banco",
  [EFFECT_TYPES.SUMMON_FROM_BENCH]: "Invocar do banco",
  [EFFECT_TYPES.RESCUE_ACTIVE]: "Resgatar ativa",
  [EFFECT_TYPES.APPLY_POISON]: "Aplicar veneno",
  [EFFECT_TYPES.APPLY_BURN]: "Aplicar queimadura",
  [EFFECT_TYPES.APPLY_FREEZE]: "Aplicar congelamento",
  [EFFECT_TYPES.APPLY_PARALYSIS]: "Aplicar paralisia",
  [EFFECT_TYPES.APPLY_CONFUSE]: "Aplicar confusao",
  [EFFECT_TYPES.APPLY_SLEEP]: "Aplicar sono",
  [EFFECT_TYPES.REMOVE_CONDITIONS]: "Remover condicoes",
  [EFFECT_TYPES.BURN]: "Queimar",
  [EFFECT_TYPES.PARALYZE]: "Paralisar",
  [EFFECT_TYPES.FREEZE]: "Congelar",
  [EFFECT_TYPES.CONFUSE]: "Confundir",
  [EFFECT_TYPES.PREVENT_ATTACK]: "Impedir ataque",
  [EFFECT_TYPES.PREVENT_RETREAT]: "Impedir recuo",
  [EFFECT_TYPES.SKIP_NEXT_ATTACK]: "Pular proximo ataque",
  [EFFECT_TYPES.CANNOT_USE_SAME_ATTACK_NEXT_TURN]: "Nao repetir ataque no proximo turno",
  [EFFECT_TYPES.BUFF_DAMAGE]: "Aumentar dano",
  [EFFECT_TYPES.BUFF_DAMAGE_THIS_TURN]: "Aumentar dano neste turno",
  [EFFECT_TYPES.BUFF_DAMAGE_NEXT_TURN]: "Aumentar dano no proximo turno",
  [EFFECT_TYPES.BUFF_EQUIPPED_CARD_DAMAGE]: "Aumentar dano da carta equipada",
  [EFFECT_TYPES.BUFF_DAMAGE_BY_TAG]: "Aumentar dano por marcador",
  [EFFECT_TYPES.BUFF_DAMAGE_BY_ATTACHED_ENERGY]: "Aumentar dano por energia anexada",
  [EFFECT_TYPES.BUFF_BASE_ATTRIBUTES]: "Aumentar atributos base",
  [EFFECT_TYPES.INCREASE_MAX_HP]: "Aumentar vida maxima",
  [EFFECT_TYPES.BUFF_HEAL_AMOUNT]: "Aumentar cura",
  [EFFECT_TYPES.DOUBLE_DAMAGE_AGAINST_TYPE]: "Dobrar dano contra tipo",
  [EFFECT_TYPES.WEAKNESS_OVERRIDE]: "Alterar fraqueza",
  [EFFECT_TYPES.ALPHA_POINT_OVERRIDE]: "Alterar pontos Alpha",
  [EFFECT_TYPES.REDUCE_DAMAGE]: "Reduzir dano",
  [EFFECT_TYPES.REDUCE_NEXT_DAMAGE]: "Reduzir proximo dano",
  [EFFECT_TYPES.HALVE_DAMAGE_TAKEN]: "Reduzir dano recebido pela metade",
  [EFFECT_TYPES.PREVENT_DAMAGE]: "Prevenir dano",
  [EFFECT_TYPES.PREVENT_DAMAGE_TYPE]: "Prevenir tipo de dano",
  [EFFECT_TYPES.IMMUNE_TO_DAMAGE_TYPE]: "Imune a tipo de dano",
  [EFFECT_TYPES.IMMUNE_TO_NEGATIVE_EFFECTS]: "Imune a efeitos negativos",
  [EFFECT_TYPES.IGNORE_TOOL_EFFECTS]: "Ignorar efeitos de ferramenta",
  [EFFECT_TYPES.REFLECT_DAMAGE]: "Refletir dano",
  [EFFECT_TYPES.REFLECT_DAMAGE_DOUBLED]: "Refletir dano dobrado",
  [EFFECT_TYPES.REFLECT_DOUBLE_DAMAGE]: "Refletir dano dobrado",
  [EFFECT_TYPES.REFLECT_HALVED_SHARED]: "Refletir metade compartilhada",
  [EFFECT_TYPES.REDIRECT_DAMAGE]: "Redirecionar dano",
  [EFFECT_TYPES.REDIRECT_DAMAGE_TO_BENCH]: "Redirecionar dano ao banco",
  [EFFECT_TYPES.SHARE_DAMAGE]: "Compartilhar dano",
  [EFFECT_TYPES.TAKE_DAMAGE_INSTEAD]: "Receber dano no lugar",
  [EFFECT_TYPES.COIN_FLIP]: "Cara ou coroa",
  [EFFECT_TYPES.DICE_ROLL]: "Rolar dado",
  [EFFECT_TYPES.IF_DICE_GREATER_THAN]: "Se dado maior que",
  [EFFECT_TYPES.IF_DICE_LESS_THAN]: "Se dado menor que",
  [EFFECT_TYPES.IF_TARGET_NATURE]: "Se alvo tiver natureza",
  [EFFECT_TYPES.IF_TARGET_TAG]: "Se alvo tiver marcador",
  [EFFECT_TYPES.IF_SELF_HAS_ENERGY_COUNT]: "Se tiver quantidade de energia",
  [EFFECT_TYPES.IF_BENCH_HAS_CARD]: "Se banco tiver carta",
  [EFFECT_TYPES.IF_BENCH_COUNT_BY_NATURE]: "Se banco tiver natureza",
  [EFFECT_TYPES.IF_HAS_TOOL_ATTACHED]: "Se tiver equipamento anexado",
  [EFFECT_TYPES.IF_CARD_WAS_ATTACKED]: "Se carta foi atacada",
  [EFFECT_TYPES.IF_CARD_KNOCKED_OUT]: "Se carta foi nocauteada",
  [EFFECT_TYPES.ON_ATTACK]: "Ao atacar",
  [EFFECT_TYPES.ON_DAMAGE_TAKEN]: "Ao receber dano",
  [EFFECT_TYPES.ON_ENERGY_ATTACHED]: "Ao anexar energia",
  [EFFECT_TYPES.ON_KNOCKOUT]: "Ao nocautear",
  [EFFECT_TYPES.ON_TURN_START]: "No inicio do turno",
  [EFFECT_TYPES.ON_TURN_END]: "No fim do turno",
  [EFFECT_TYPES.COPY_OPPONENT_ITEM]: "Copiar item do oponente",
  [EFFECT_TYPES.TRANSFORM_INTO_BENCH_CARD]: "Transformar em carta do banco",
  [EFFECT_TYPES.TRANSFORM_INTO_OPPONENT_BENCH_CARD]: "Transformar em carta do banco oponente",
  [EFFECT_TYPES.ABSORB_OWN_BENCH_CARD]: "Absorver carta do proprio banco",
  [EFFECT_TYPES.CREATE_TEMPORARY_UNIT]: "Criar unidade temporaria",
  [EFFECT_TYPES.PLAY_ITEM_AS_UNIT]: "Jogar item como unidade",
  [EFFECT_TYPES.POISON]: "Envenenar",
  [EFFECT_TYPES.DAMAGE_OVER_TIME]: "Dano por turno",
  [EFFECT_TYPES.INSTANT_KNOCKOUT_IF_DAMAGE_TYPE]: "Nocaute por tipo de dano",
  [EFFECT_TYPES.COUNTER_DAMAGE]: "Contra-atacar com dano",
  [EFFECT_TYPES.CANCEL_KNOCKOUT]: "Cancelar nocaute",
  [EFFECT_TYPES.RETURN_TO_HAND_ON_KO]: "Voltar para mao no nocaute",
  [EFFECT_TYPES.RETURN_TO_DECK_ON_KO]: "Voltar para deck no nocaute",
  [EFFECT_TYPES.RETURN_KNOCKED_OUT_TO_HAND]: "Nocauteado volta para mao",
  [EFFECT_TYPES.PREVENT_POINT_GAIN]: "Impedir ganho de ponto",
  [EFFECT_TYPES.CANCEL_KNOCKOUT_POINT]: "Cancelar ponto de nocaute",
  [EFFECT_TYPES.SEARCH_CARD_BY_FILTER]: "Buscar carta por filtro",
  [EFFECT_TYPES.STATUS_ON_ATTACKER]: "Status no atacante",
  [EFFECT_TYPES.DISCARD_EQUIPMENT_AFTER_TRIGGER]: "Descartar equipamento apos ativar",
  [EFFECT_TYPES.DISABLE_SAME_ATTACK_NEXT_TURN]: "Desabilitar mesmo ataque no proximo turno",
};

export const TARGETS = {
  ACTIVE: "ACTIVE",
  BENCH: "BENCH",
  ANY: "ANY",
  ALL_ENEMY: "ALL_ENEMY",
  ALL_ALLY: "ALL_ALLY",
  SELF: "SELF",
  SELF_ACTIVE: "SELF_ACTIVE",
  SELF_BENCH: "SELF_BENCH",
  SELF_BENCH_RANDOM: "SELF_BENCH_RANDOM",
  SELF_BENCH_CHOOSE: "SELF_BENCH_CHOOSE",
  SELF_BENCH_BY_NATURE: "SELF_BENCH_BY_NATURE",
  SELF_BENCH_BY_NAME: "SELF_BENCH_BY_NAME",
  ANY_SELF_CARD: "ANY_SELF_CARD",
  ALL_SELF_CARDS: "ALL_SELF_CARDS",
  ALL_SELF_BENCH: "ALL_SELF_BENCH",
  EQUIPPED_CARD: "EQUIPPED_CARD",
  DAMAGE_SOURCE: "DAMAGE_SOURCE",
  DAMAGE_TARGET: "DAMAGE_TARGET",
  OPPONENT_ACTIVE: "OPPONENT_ACTIVE",
  OPPONENT_BENCH: "OPPONENT_BENCH",
  OPPONENT_BENCH_RANDOM: "OPPONENT_BENCH_RANDOM",
  OPPONENT_BENCH_CHOOSE: "OPPONENT_BENCH_CHOOSE",
  ANY_BENCH_CHOOSE: "ANY_BENCH_CHOOSE",
  ANY_OPPONENT_CARD: "ANY_OPPONENT_CARD",
  ALL_OPPONENT_CARDS: "ALL_OPPONENT_CARDS",
  ALL_OPPONENT_BENCH: "ALL_OPPONENT_BENCH",
  PREVIOUSLY_DAMAGED_OPPONENT: "PREVIOUSLY_DAMAGED_OPPONENT",
};

export const TARGET_LABELS = {
  [TARGETS.ACTIVE]: "Ativa",
  [TARGETS.BENCH]: "Banco",
  [TARGETS.ANY]: "Qualquer alvo",
  [TARGETS.ALL_ENEMY]: "Todos inimigos",
  [TARGETS.ALL_ALLY]: "Todos aliados",
  [TARGETS.SELF]: "Voce",
  [TARGETS.SELF_ACTIVE]: "Sua ativa",
  [TARGETS.SELF_BENCH]: "Seu banco",
  [TARGETS.SELF_BENCH_RANDOM]: "Banco proprio aleatorio",
  [TARGETS.SELF_BENCH_CHOOSE]: "Escolha do seu banco",
  [TARGETS.SELF_BENCH_BY_NATURE]: "Banco proprio por natureza",
  [TARGETS.SELF_BENCH_BY_NAME]: "Banco proprio por nome",
  [TARGETS.ANY_SELF_CARD]: "Qualquer sua",
  [TARGETS.ALL_SELF_CARDS]: "Todas suas",
  [TARGETS.ALL_SELF_BENCH]: "Todo seu banco",
  [TARGETS.EQUIPPED_CARD]: "Carta equipada",
  [TARGETS.DAMAGE_SOURCE]: "Fonte do dano",
  [TARGETS.DAMAGE_TARGET]: "Alvo do dano",
  [TARGETS.OPPONENT_ACTIVE]: "Ativa oponente",
  [TARGETS.OPPONENT_BENCH]: "Banco oponente",
  [TARGETS.OPPONENT_BENCH_RANDOM]: "Banco oponente aleatorio",
  [TARGETS.OPPONENT_BENCH_CHOOSE]: "Escolha do banco oponente",
  [TARGETS.ANY_BENCH_CHOOSE]: "Escolha qualquer banco",
  [TARGETS.ANY_OPPONENT_CARD]: "Qualquer oponente",
  [TARGETS.ALL_OPPONENT_CARDS]: "Todas oponente",
  [TARGETS.ALL_OPPONENT_BENCH]: "Todo banco oponente",
  [TARGETS.PREVIOUSLY_DAMAGED_OPPONENT]: "Oponente ja ferido",
};

export const DURATIONS = {
  INSTANT: "INSTANT",
  NEXT_DAMAGE: "NEXT_DAMAGE",
  THIS_TURN: "THIS_TURN",
  NEXT_TURN: "NEXT_TURN",
  UNTIL_TURN_END: "UNTIL_TURN_END",
  UNTIL_CONDITION_CLEARED: "UNTIL_CONDITION_CLEARED",
  UNTIL_LEAVES_ACTIVE: "UNTIL_LEAVES_ACTIVE",
  UNTIL_RETURNS_TO_BENCH: "UNTIL_RETURNS_TO_BENCH",
  UNTIL_KNOCKED_OUT: "UNTIL_KNOCKED_OUT",
  PERMANENT_WHILE_IN_PLAY: "PERMANENT_WHILE_IN_PLAY",
  ONCE_PER_TURN: "ONCE_PER_TURN",
};

export const DURATION_LABELS = {
  [DURATIONS.INSTANT]: "Instantaneo",
  [DURATIONS.NEXT_DAMAGE]: "Proximo dano",
  [DURATIONS.THIS_TURN]: "Neste turno",
  [DURATIONS.NEXT_TURN]: "Proximo turno",
  [DURATIONS.UNTIL_TURN_END]: "Ate o fim do turno",
  [DURATIONS.UNTIL_CONDITION_CLEARED]: "Ate limpar condicao",
  [DURATIONS.UNTIL_LEAVES_ACTIVE]: "Ate sair da ativa",
  [DURATIONS.UNTIL_RETURNS_TO_BENCH]: "Ate voltar ao banco",
  [DURATIONS.UNTIL_KNOCKED_OUT]: "Ate ser nocauteado",
  [DURATIONS.PERMANENT_WHILE_IN_PLAY]: "Enquanto em jogo",
  [DURATIONS.ONCE_PER_TURN]: "Uma vez por turno",
};

export const EFFECT_CONDITIONS = {
  ALWAYS: "",
  ON_EQUIP: "ON_EQUIP",
  EQUIPPED_CARD_DEALS_DAMAGE: "EQUIPPED_CARD_DEALS_DAMAGE",
  EQUIPPED_CARD_TAKES_DAMAGE: "EQUIPPED_CARD_TAKES_DAMAGE",
  EQUIPPED_CARD_HAS_EQUIPMENT: "EQUIPPED_CARD_HAS_EQUIPMENT",
};

export const EFFECT_CONDITION_LABELS = {
  [EFFECT_CONDITIONS.ALWAYS]: "Sem condicao",
  [EFFECT_CONDITIONS.ON_EQUIP]: "Ao equipar",
  [EFFECT_CONDITIONS.EQUIPPED_CARD_DEALS_DAMAGE]: "Quando carta equipada causa dano",
  [EFFECT_CONDITIONS.EQUIPPED_CARD_TAKES_DAMAGE]: "Quando carta equipada recebe dano",
  [EFFECT_CONDITIONS.EQUIPPED_CARD_HAS_EQUIPMENT]: "Se tiver equipamento anexado",
};

export const CANONICAL_EFFECT_TYPES = new Set([
  EFFECT_TYPES.DAMAGE,
  EFFECT_TYPES.DAMAGE_BY_FORMULA,
  EFFECT_TYPES.DAMAGE_RANDOM_TARGETS,
  EFFECT_TYPES.DAMAGE_ANY_TARGET,
  EFFECT_TYPES.DAMAGE_ACTIVE_AND_BENCH,
  EFFECT_TYPES.DAMAGE_ALL_OPPONENT_BENCH,
  EFFECT_TYPES.DAMAGE_SELF,
  EFFECT_TYPES.DAMAGE_EXTRA_BY_ENERGY,
  EFFECT_TYPES.DAMAGE_EXTRA_BY_BENCH_CARD,
  EFFECT_TYPES.DAMAGE_EXTRA_BY_TARGET_TYPE,
  EFFECT_TYPES.DAMAGE_EXTRA_BY_DICE,
  EFFECT_TYPES.DAMAGE_EXTRA_BY_COIN,
  EFFECT_TYPES.DAMAGE_CONSECUTIVE_STACK,
  EFFECT_TYPES.DAMAGE_SPLIT,
  EFFECT_TYPES.DAMAGE_TO_PREVIOUSLY_DAMAGED_BENCH,
  EFFECT_TYPES.HEAL,
  EFFECT_TYPES.HEAL_BY_DAMAGE_DEALT,
  EFFECT_TYPES.HEAL_PER_TURN,
  EFFECT_TYPES.GAIN_HP_FROM_KO,
  EFFECT_TYPES.ADD_ENERGY,
  EFFECT_TYPES.ADD_TYPED_ENERGY,
  EFFECT_TYPES.ADD_ENERGY_BY_COIN,
  EFFECT_TYPES.ADD_ENERGY_BY_DAMAGE_TAKEN,
  EFFECT_TYPES.ADD_ENERGY_ON_ATTACK,
  EFFECT_TYPES.MOVE_ENERGY,
  EFFECT_TYPES.MOVE_ALL_ENERGY_FROM_BENCH_TO_ACTIVE,
  EFFECT_TYPES.REMOVE_ENERGY,
  EFFECT_TYPES.REMOVE_RANDOM_ENERGY,
  EFFECT_TYPES.DISCARD_OWN_ENERGY,
  EFFECT_TYPES.ENERGY_ANY_TYPE,
  EFFECT_TYPES.ENERGY_COST_REDUCTION,
  EFFECT_TYPES.ENERGY_REQUIRED_TYPE,
  EFFECT_TYPES.DRAW_CARD,
  EFFECT_TYPES.DRAW_MULTIPLE,
  EFFECT_TYPES.SEARCH_RANDOM_BASIC,
  EFFECT_TYPES.SEARCH_CARD_BY_FILTER,
  EFFECT_TYPES.LOOK_TOP_DECK,
  EFFECT_TYPES.REVEAL_OPPONENT_HAND,
  EFFECT_TYPES.REVEAL_ONE_CARD,
  EFFECT_TYPES.SHUFFLE_OPPONENT_HAND,
  EFFECT_TYPES.OPPONENT_DRAWS_RANDOM,
  EFFECT_TYPES.SWAP_HAND_CARD_RANDOM,
  EFFECT_TYPES.FORCE_OPPONENT_SWAP_CARD,
  EFFECT_TYPES.RETURN_CARD_TO_DECK,
  EFFECT_TYPES.RESURRECT_TO_DECK,
  EFFECT_TYPES.RESURRECT_FROM_DISCARD,
  EFFECT_TYPES.DISCARD_CARD,
  EFFECT_TYPES.SWITCH_OWN_ACTIVE,
  EFFECT_TYPES.SWITCH_OPPONENT_ACTIVE,
  EFFECT_TYPES.FORCE_SWITCH_OPPONENT_ACTIVE,
  EFFECT_TYPES.OPPONENT_CHOOSES_NEW_ACTIVE,
  EFFECT_TYPES.PROMOTE_FROM_BENCH,
  EFFECT_TYPES.RESCUE_ACTIVE,
  EFFECT_TYPES.TAKE_DAMAGE_INSTEAD,
  EFFECT_TYPES.POISON,
  EFFECT_TYPES.BURN,
  EFFECT_TYPES.FREEZE,
  EFFECT_TYPES.PARALYZE,
  EFFECT_TYPES.CONFUSE,
  EFFECT_TYPES.PREVENT_ATTACK,
  EFFECT_TYPES.PREVENT_RETREAT,
  EFFECT_TYPES.BLOCK_RETREAT,
  EFFECT_TYPES.SKIP_NEXT_ATTACK,
  EFFECT_TYPES.CANNOT_USE_SAME_ATTACK_NEXT_TURN,
  EFFECT_TYPES.DAMAGE_OVER_TIME,
  EFFECT_TYPES.REMOVE_CONDITIONS,
  EFFECT_TYPES.STATUS_ON_ATTACKER,
  EFFECT_TYPES.BUFF_DAMAGE,
  EFFECT_TYPES.BUFF_DAMAGE_THIS_TURN,
  EFFECT_TYPES.BUFF_DAMAGE_NEXT_TURN,
  EFFECT_TYPES.BUFF_EQUIPPED_CARD_DAMAGE,
  EFFECT_TYPES.BUFF_DAMAGE_BY_TAG,
  EFFECT_TYPES.BUFF_DAMAGE_BY_ATTACHED_ENERGY,
  EFFECT_TYPES.BUFF_BASE_ATTRIBUTES,
  EFFECT_TYPES.INCREASE_MAX_HP,
  EFFECT_TYPES.BUFF_HEAL_AMOUNT,
  EFFECT_TYPES.DOUBLE_DAMAGE_AGAINST_TYPE,
  EFFECT_TYPES.WEAKNESS_OVERRIDE,
  EFFECT_TYPES.ALPHA_POINT_OVERRIDE,
  EFFECT_TYPES.IGNORE_RETREAT_COST,
  EFFECT_TYPES.REDUCE_RETREAT_COST,
  EFFECT_TYPES.ATTACK_FROM_BENCH,
  EFFECT_TYPES.REDUCE_DAMAGE,
  EFFECT_TYPES.REDUCE_NEXT_DAMAGE,
  EFFECT_TYPES.HALVE_DAMAGE_TAKEN,
  EFFECT_TYPES.PREVENT_DAMAGE,
  EFFECT_TYPES.PREVENT_DAMAGE_TYPE,
  EFFECT_TYPES.IMMUNE_TO_DAMAGE_TYPE,
  EFFECT_TYPES.IMMUNE_TO_NEGATIVE_EFFECTS,
  EFFECT_TYPES.IGNORE_TOOL_EFFECTS,
  EFFECT_TYPES.REFLECT_DAMAGE,
  EFFECT_TYPES.REFLECT_DOUBLE_DAMAGE,
  EFFECT_TYPES.REDIRECT_DAMAGE,
  EFFECT_TYPES.SHARE_DAMAGE,
  EFFECT_TYPES.COUNTER_DAMAGE,
  EFFECT_TYPES.CANCEL_KNOCKOUT,
  EFFECT_TYPES.RETURN_KNOCKED_OUT_TO_HAND,
  EFFECT_TYPES.RETURN_TO_DECK_ON_KO,
  EFFECT_TYPES.PREVENT_POINT_GAIN,
  EFFECT_TYPES.CANCEL_KNOCKOUT_POINT,
  EFFECT_TYPES.COIN_FLIP,
  EFFECT_TYPES.DICE_ROLL,
  EFFECT_TYPES.COPY_OPPONENT_ITEM,
  EFFECT_TYPES.TRANSFORM_INTO_OPPONENT_BENCH_CARD,
  EFFECT_TYPES.ABSORB_OWN_BENCH_CARD,
  EFFECT_TYPES.CREATE_TEMPORARY_UNIT,
  EFFECT_TYPES.PLAY_ITEM_AS_UNIT,
  EFFECT_TYPES.DISCARD_EQUIPMENT_AFTER_TRIGGER,
]);

export const EFFECT_TYPE_ALIASES = {
  [EFFECT_TYPES.ENERGY_GAIN]: EFFECT_TYPES.ADD_ENERGY,
  [EFFECT_TYPES.ENERGY_REMOVE]: EFFECT_TYPES.REMOVE_ENERGY,
  [EFFECT_TYPES.ADD_ENERGY_TYPED]: EFFECT_TYPES.ADD_TYPED_ENERGY,
  [EFFECT_TYPES.ADD_ENERGY_TO_TARGET]: EFFECT_TYPES.ADD_ENERGY,
  [EFFECT_TYPES.ADD_ENERGY_TO_ACTIVE]: EFFECT_TYPES.ADD_ENERGY,
  [EFFECT_TYPES.ADD_ENERGY_TO_BENCH]: EFFECT_TYPES.ADD_ENERGY,
  [EFFECT_TYPES.ADD_MULTIPLE_ENERGY]: EFFECT_TYPES.ADD_ENERGY,
  [EFFECT_TYPES.ALLOW_ANY_ENERGY_TYPE]: EFFECT_TYPES.ENERGY_ANY_TYPE,
  [EFFECT_TYPES.MOVE_ALL_BENCH_ENERGY_TO_ACTIVE]: EFFECT_TYPES.MOVE_ALL_ENERGY_FROM_BENCH_TO_ACTIVE,
  [EFFECT_TYPES.APPLY_POISON]: EFFECT_TYPES.POISON,
  [EFFECT_TYPES.APPLY_BURN]: EFFECT_TYPES.BURN,
  [EFFECT_TYPES.APPLY_FREEZE]: EFFECT_TYPES.FREEZE,
  [EFFECT_TYPES.APPLY_PARALYSIS]: EFFECT_TYPES.PARALYZE,
  [EFFECT_TYPES.APPLY_CONFUSE]: EFFECT_TYPES.CONFUSE,
  [EFFECT_TYPES.APPLY_SLEEP]: EFFECT_TYPES.PREVENT_ATTACK,
  [EFFECT_TYPES.REMOVE_CONDITION]: EFFECT_TYPES.REMOVE_CONDITIONS,
  [EFFECT_TYPES.HEAL_SELF]: EFFECT_TYPES.HEAL,
  [EFFECT_TYPES.HEAL_ACTIVE]: EFFECT_TYPES.HEAL,
  [EFFECT_TYPES.HEAL_BENCH]: EFFECT_TYPES.HEAL,
  [EFFECT_TYPES.HEAL_BENCH_CARD]: EFFECT_TYPES.HEAL,
  [EFFECT_TYPES.HEAL_ANY_SELF_CARD]: EFFECT_TYPES.HEAL,
  [EFFECT_TYPES.HEAL_ANY_ALLY]: EFFECT_TYPES.HEAL,
  [EFFECT_TYPES.HEAL_EQUIPPED_CARD]: EFFECT_TYPES.HEAL,
  [EFFECT_TYPES.HEAL_ON_ENERGY_ATTACH]: EFFECT_TYPES.HEAL,
  [EFFECT_TYPES.HEAL_ALLY_ON_DAMAGE]: EFFECT_TYPES.HEAL,
  [EFFECT_TYPES.HEAL_BENCH_GROUP]: EFFECT_TYPES.HEAL,
  [EFFECT_TYPES.DAMAGE_FIXED]: EFFECT_TYPES.DAMAGE,
  [EFFECT_TYPES.DAMAGE_MODIFIER]: EFFECT_TYPES.BUFF_DAMAGE,
  [EFFECT_TYPES.DAMAGE_REDIRECT]: EFFECT_TYPES.REDIRECT_DAMAGE,
  [EFFECT_TYPES.REFLECT_DAMAGE_DOUBLED]: EFFECT_TYPES.REFLECT_DOUBLE_DAMAGE,
  [EFFECT_TYPES.REDIRECT_DAMAGE_TO_BENCH]: EFFECT_TYPES.REDIRECT_DAMAGE,
  [EFFECT_TYPES.FORCE_RETREAT]: EFFECT_TYPES.FORCE_SWITCH_OPPONENT_ACTIVE,
  [EFFECT_TYPES.SUMMON_FROM_BENCH]: EFFECT_TYPES.PROMOTE_FROM_BENCH,
  [EFFECT_TYPES.OPPONENT_DRAWS_LIMITED]: EFFECT_TYPES.OPPONENT_DRAWS_RANDOM,
  [EFFECT_TYPES.REVEAL_ONE_OPPONENT_CARD]: EFFECT_TYPES.REVEAL_ONE_CARD,
  [EFFECT_TYPES.RETURN_TO_HAND_ON_KO]: EFFECT_TYPES.RETURN_KNOCKED_OUT_TO_HAND,
  [EFFECT_TYPES.COPY_ITEM]: EFFECT_TYPES.COPY_OPPONENT_ITEM,
  [EFFECT_TYPES.REVIVE]: EFFECT_TYPES.RESURRECT_FROM_DISCARD,
  [EFFECT_TYPES.TRANSFORM]: EFFECT_TYPES.TRANSFORM_INTO_OPPONENT_BENCH_CARD,
  [EFFECT_TYPES.TRANSFORM_INTO_BENCH_CARD]: EFFECT_TYPES.TRANSFORM_INTO_OPPONENT_BENCH_CARD,
  [EFFECT_TYPES.REFLECT_HALVED_SHARED]: EFFECT_TYPES.SHARE_DAMAGE,
  [EFFECT_TYPES.DISABLE_SAME_ATTACK_NEXT_TURN]: EFFECT_TYPES.CANNOT_USE_SAME_ATTACK_NEXT_TURN,
};

export const DUPLICATE_EFFECT_TYPE_ALIASES = EFFECT_TYPE_ALIASES;

export const EQUIPMENT_DAMAGE_BONUS_EFFECT_TYPES = new Set([
  EFFECT_TYPES.BUFF_DAMAGE,
  EFFECT_TYPES.BUFF_DAMAGE_THIS_TURN,
  EFFECT_TYPES.BUFF_DAMAGE_NEXT_TURN,
  EFFECT_TYPES.BUFF_EQUIPPED_CARD_DAMAGE,
  EFFECT_TYPES.BUFF_DAMAGE_BY_TAG,
  EFFECT_TYPES.BUFF_DAMAGE_BY_ATTACHED_ENERGY,
]);

export const EQUIPMENT_ON_EQUIP_EFFECT_TYPES = new Set([
  EFFECT_TYPES.HEAL,
  EFFECT_TYPES.ADD_ENERGY,
  EFFECT_TYPES.ADD_TYPED_ENERGY,
  EFFECT_TYPES.BURN,
  EFFECT_TYPES.PARALYZE,
  EFFECT_TYPES.FREEZE,
  EFFECT_TYPES.CONFUSE,
  EFFECT_TYPES.PREVENT_ATTACK,
  EFFECT_TYPES.PREVENT_RETREAT,
  EFFECT_TYPES.SKIP_NEXT_ATTACK,
  EFFECT_TYPES.CANNOT_USE_SAME_ATTACK_NEXT_TURN,
  EFFECT_TYPES.BUFF_BASE_ATTRIBUTES,
  EFFECT_TYPES.INCREASE_MAX_HP,
  EFFECT_TYPES.BUFF_HEAL_AMOUNT,
  EFFECT_TYPES.DOUBLE_DAMAGE_AGAINST_TYPE,
  EFFECT_TYPES.WEAKNESS_OVERRIDE,
  EFFECT_TYPES.ALPHA_POINT_OVERRIDE,
  EFFECT_TYPES.REDUCE_DAMAGE,
  EFFECT_TYPES.REDUCE_NEXT_DAMAGE,
  EFFECT_TYPES.PREVENT_DAMAGE,
  EFFECT_TYPES.IMMUNE_TO_DAMAGE_TYPE,
  EFFECT_TYPES.IMMUNE_TO_NEGATIVE_EFFECTS,
  EFFECT_TYPES.IGNORE_TOOL_EFFECTS,
  EFFECT_TYPES.HALVE_DAMAGE_TAKEN,
  EFFECT_TYPES.REFLECT_DAMAGE,
  EFFECT_TYPES.REFLECT_DOUBLE_DAMAGE,
  EFFECT_TYPES.REDIRECT_DAMAGE,
  EFFECT_TYPES.SHARE_DAMAGE,
  EFFECT_TYPES.ENERGY_ANY_TYPE,
  EFFECT_TYPES.ENERGY_COST_REDUCTION,
  EFFECT_TYPES.ENERGY_REQUIRED_TYPE,
  EFFECT_TYPES.IGNORE_RETREAT_COST,
  EFFECT_TYPES.REDUCE_RETREAT_COST,
  EFFECT_TYPES.BLOCK_RETREAT,
  EFFECT_TYPES.ATTACK_FROM_BENCH,
]);

export const ABILITY_TRIGGERS = {
  BEFORE_ATTACK: "BEFORE_ATTACK",
  ON_ATTACK: "ON_ATTACK",
  ON_RECEIVE_DAMAGE: "ON_RECEIVE_DAMAGE",
  ON_KO: "ON_KO",
  ON_OPPONENT_KO: "ON_OPPONENT_KO",
  PASSIVE_ACTIVE: "PASSIVE_ACTIVE",
  PASSIVE_BENCH: "PASSIVE_BENCH",
  ON_ITEM_USE: "ON_ITEM_USE",
  ON_ITEM_USED: "ON_ITEM_USED",
  ON_SUPPORT_PLAYED: "ON_SUPPORT_PLAYED",
  ON_RETREAT: "ON_RETREAT",
  ON_EVOLVE: "ON_EVOLVE",
  ON_ENTER_ACTIVE: "ON_ENTER_ACTIVE",
  INTERRUPT: "INTERRUPT",
  BEFORE_DAMAGE_TAKEN: "BEFORE_DAMAGE_TAKEN",
  BEFORE_DAMAGE_APPLIED: "BEFORE_DAMAGE_APPLIED",
  BEFORE_ALLY_ACTIVE_TAKES_DAMAGE: "BEFORE_ALLY_ACTIVE_TAKES_DAMAGE",
  ALLY_ACTIVE_WOULD_BE_KNOCKED_OUT: "ALLY_ACTIVE_WOULD_BE_KNOCKED_OUT",
  BEFORE_KNOCKOUT: "BEFORE_KNOCKOUT",
  ON_DAMAGE_TAKEN: "ON_DAMAGE_TAKEN",
  AFTER_DAMAGE_APPLIED: "AFTER_DAMAGE_APPLIED",
  ON_CONDITION_APPLIED: "ON_CONDITION_APPLIED",
  ALLY_ACTIVE_TAKES_DAMAGE: "ALLY_ACTIVE_TAKES_DAMAGE",
  ON_ENERGY_ATTACHED: "ON_ENERGY_ATTACHED",
  ON_TURN_START: "ON_TURN_START",
  ON_TURN_END: "ON_TURN_END",
  ON_KNOCKOUT: "ON_KNOCKOUT",
  AFTER_KNOCKOUT: "AFTER_KNOCKOUT",
  ON_CARD_LEFT_FIELD: "ON_CARD_LEFT_FIELD",
};

export const ABILITY_TRIGGER_LABELS = {
  [ABILITY_TRIGGERS.BEFORE_ATTACK]: "Antes de atacar",
  [ABILITY_TRIGGERS.ON_ATTACK]: "Ao atacar",
  [ABILITY_TRIGGERS.ON_RECEIVE_DAMAGE]: "Ao receber dano",
  [ABILITY_TRIGGERS.ON_KO]: "Ao ser nocauteada",
  [ABILITY_TRIGGERS.ON_OPPONENT_KO]: "Ao nocautear oponente",
  [ABILITY_TRIGGERS.PASSIVE_ACTIVE]: "Passiva na ativa",
  [ABILITY_TRIGGERS.PASSIVE_BENCH]: "Passiva no banco",
  [ABILITY_TRIGGERS.ON_ITEM_USE]: "Ao usar item",
  [ABILITY_TRIGGERS.ON_ITEM_USED]: "Ao usar item",
  [ABILITY_TRIGGERS.ON_SUPPORT_PLAYED]: "Ao jogar suporte",
  [ABILITY_TRIGGERS.ON_RETREAT]: "Ao recuar",
  [ABILITY_TRIGGERS.ON_EVOLVE]: "Ao evoluir",
  [ABILITY_TRIGGERS.ON_ENTER_ACTIVE]: "Ao entrar na ativa",
  [ABILITY_TRIGGERS.INTERRUPT]: "Interrupcao",
  [ABILITY_TRIGGERS.BEFORE_DAMAGE_TAKEN]: "Antes de receber dano",
  [ABILITY_TRIGGERS.BEFORE_DAMAGE_APPLIED]: "Antes de aplicar dano",
  [ABILITY_TRIGGERS.BEFORE_ALLY_ACTIVE_TAKES_DAMAGE]: "Antes da ativa aliada receber dano",
  [ABILITY_TRIGGERS.ALLY_ACTIVE_WOULD_BE_KNOCKED_OUT]: "Quando ativa aliada seria nocauteada",
  [ABILITY_TRIGGERS.BEFORE_KNOCKOUT]: "Antes do nocaute",
  [ABILITY_TRIGGERS.ON_DAMAGE_TAKEN]: "Ao receber dano",
  [ABILITY_TRIGGERS.AFTER_DAMAGE_APPLIED]: "Depois de aplicar dano",
  [ABILITY_TRIGGERS.ON_CONDITION_APPLIED]: "Ao aplicar condicao",
  [ABILITY_TRIGGERS.ALLY_ACTIVE_TAKES_DAMAGE]: "Quando aliada ativa recebe dano",
  [ABILITY_TRIGGERS.ON_ENERGY_ATTACHED]: "Ao anexar energia",
  [ABILITY_TRIGGERS.ON_TURN_START]: "No inicio do turno",
  [ABILITY_TRIGGERS.ON_TURN_END]: "No fim do turno",
  [ABILITY_TRIGGERS.ON_KNOCKOUT]: "Ao nocautear",
  [ABILITY_TRIGGERS.AFTER_KNOCKOUT]: "Depois do nocaute",
  [ABILITY_TRIGGERS.ON_CARD_LEFT_FIELD]: "Ao sair do campo",
};

export const ABILITY_CONDITION_TYPES = {
  SOURCE_IS_ACTIVE: "SOURCE_IS_ACTIVE",
  SOURCE_IS_ON_BENCH: "SOURCE_IS_ON_BENCH",
  TARGET_IS_ACTIVE: "TARGET_IS_ACTIVE",
  TARGET_IS_ON_BENCH: "TARGET_IS_ON_BENCH",
  SOURCE_POSITION: "SOURCE_POSITION",
  TARGET_POSITION: "TARGET_POSITION",
  TARGET_NATURE_IN: "TARGET_NATURE_IN",
  SOURCE_NATURE_IN: "SOURCE_NATURE_IN",
  TARGET_CARD_TYPE_IN: "TARGET_CARD_TYPE_IN",
  SOURCE_CARD_TYPE_IN: "SOURCE_CARD_TYPE_IN",
  TARGET_IS_DAMAGED: "TARGET_IS_DAMAGED",
  SELF_HAS_ENERGY_TYPE: "SELF_HAS_ENERGY_TYPE",
  SELF_ENERGY_COUNT_GTE: "SELF_ENERGY_COUNT_GTE",
  TARGET_ENERGY_COUNT_GTE: "TARGET_ENERGY_COUNT_GTE",
  BENCH_HAS_CARD_NAME: "BENCH_HAS_CARD_NAME",
  TARGET_IS_CARD_NAME: "TARGET_IS_CARD_NAME",
  BENCH_HAS_NATURE: "BENCH_HAS_NATURE",
  BENCH_COUNT_BY_NATURE: "BENCH_COUNT_BY_NATURE",
  HAS_EQUIPMENT: "HAS_EQUIPMENT",
  TARGET_HAS_EQUIPMENT: "TARGET_HAS_EQUIPMENT",
  SOURCE_HAS_EQUIPMENT: "SOURCE_HAS_EQUIPMENT",
  SOURCE_HAS_NO_EQUIPMENT: "SOURCE_HAS_NO_EQUIPMENT",
  TARGET_HAS_ENERGY: "TARGET_HAS_ENERGY",
  SELF_ENERGY_EQUALS: "SELF_ENERGY_EQUALS",
  TARGET_HAS_TAG: "TARGET_HAS_TAG",
  TARGET_USES_ELEMENT: "TARGET_USES_ELEMENT",
  TARGET_META_IN: "TARGET_META_IN",
  SOURCE_META_IN: "SOURCE_META_IN",
  SOURCE_WAS_ATTACKED: "SOURCE_WAS_ATTACKED",
  SOURCE_HAS_CONDITION: "SOURCE_HAS_CONDITION",
  TARGET_HAS_CONDITION: "TARGET_HAS_CONDITION",
  DICE_RESULT_GTE: "DICE_RESULT_GTE",
  DICE_RESULT_LTE: "DICE_RESULT_LTE",
  COIN_IS_HEADS: "COIN_IS_HEADS",
  COIN_IS_TAILS: "COIN_IS_TAILS",
  IS_OWN_TURN: "IS_OWN_TURN",
  IS_OPPONENT_TURN: "IS_OPPONENT_TURN",
  SUPPORT_IS_ACTIVE: "SUPPORT_IS_ACTIVE",
  DAMAGE_AMOUNT_GTE: "DAMAGE_AMOUNT_GTE",
  WOULD_BE_KNOCKED_OUT: "WOULD_BE_KNOCKED_OUT",
  ONCE_PER_TURN: "ONCE_PER_TURN",
  SOURCE_META_VALUE_IN: "SOURCE_META_VALUE_IN",
  TARGET_META_VALUE_IN: "TARGET_META_VALUE_IN",
};

export const ABILITY_CONDITION_LABELS = {
  [ABILITY_CONDITION_TYPES.SOURCE_IS_ACTIVE]: "Fonte esta ativa",
  [ABILITY_CONDITION_TYPES.SOURCE_IS_ON_BENCH]: "Fonte esta no banco",
  [ABILITY_CONDITION_TYPES.TARGET_IS_ACTIVE]: "Alvo esta ativo",
  [ABILITY_CONDITION_TYPES.TARGET_IS_ON_BENCH]: "Alvo esta no banco",
  [ABILITY_CONDITION_TYPES.SOURCE_POSITION]: "Posicao da fonte",
  [ABILITY_CONDITION_TYPES.TARGET_POSITION]: "Posicao do alvo",
  [ABILITY_CONDITION_TYPES.TARGET_NATURE_IN]: "Natureza do alvo esta em",
  [ABILITY_CONDITION_TYPES.SOURCE_NATURE_IN]: "Natureza da fonte esta em",
  [ABILITY_CONDITION_TYPES.TARGET_CARD_TYPE_IN]: "Tipo da carta alvo esta em",
  [ABILITY_CONDITION_TYPES.SOURCE_CARD_TYPE_IN]: "Tipo da carta fonte esta em",
  [ABILITY_CONDITION_TYPES.TARGET_IS_DAMAGED]: "Alvo esta ferido",
  [ABILITY_CONDITION_TYPES.SELF_HAS_ENERGY_TYPE]: "Fonte tem energia",
  [ABILITY_CONDITION_TYPES.SELF_ENERGY_COUNT_GTE]: "Fonte tem energia minima",
  [ABILITY_CONDITION_TYPES.TARGET_ENERGY_COUNT_GTE]: "Alvo tem energia minima",
  [ABILITY_CONDITION_TYPES.BENCH_HAS_CARD_NAME]: "Banco tem carta pelo nome",
  [ABILITY_CONDITION_TYPES.TARGET_IS_CARD_NAME]: "Alvo e carta pelo nome",
  [ABILITY_CONDITION_TYPES.BENCH_HAS_NATURE]: "Banco tem natureza",
  [ABILITY_CONDITION_TYPES.BENCH_COUNT_BY_NATURE]: "Quantidade no banco por natureza",
  [ABILITY_CONDITION_TYPES.HAS_EQUIPMENT]: "Tem equipamento",
  [ABILITY_CONDITION_TYPES.TARGET_HAS_EQUIPMENT]: "Alvo tem equipamento",
  [ABILITY_CONDITION_TYPES.SOURCE_HAS_EQUIPMENT]: "Fonte tem equipamento",
  [ABILITY_CONDITION_TYPES.SOURCE_HAS_NO_EQUIPMENT]: "Fonte sem equipamento",
  [ABILITY_CONDITION_TYPES.TARGET_HAS_ENERGY]: "Alvo tem energia",
  [ABILITY_CONDITION_TYPES.SELF_ENERGY_EQUALS]: "Energia da fonte igual a",
  [ABILITY_CONDITION_TYPES.TARGET_HAS_TAG]: "Alvo tem marcador",
  [ABILITY_CONDITION_TYPES.TARGET_USES_ELEMENT]: "Alvo usa elemento",
  [ABILITY_CONDITION_TYPES.TARGET_META_IN]: "Meta do alvo esta em",
  [ABILITY_CONDITION_TYPES.SOURCE_META_IN]: "Meta da fonte esta em",
  [ABILITY_CONDITION_TYPES.SOURCE_WAS_ATTACKED]: "Fonte foi atacada",
  [ABILITY_CONDITION_TYPES.SOURCE_HAS_CONDITION]: "Fonte tem condicao",
  [ABILITY_CONDITION_TYPES.TARGET_HAS_CONDITION]: "Alvo tem condicao",
  [ABILITY_CONDITION_TYPES.DICE_RESULT_GTE]: "Resultado do dado maior ou igual",
  [ABILITY_CONDITION_TYPES.DICE_RESULT_LTE]: "Resultado do dado menor ou igual",
  [ABILITY_CONDITION_TYPES.COIN_IS_HEADS]: "Moeda deu cara",
  [ABILITY_CONDITION_TYPES.COIN_IS_TAILS]: "Moeda deu coroa",
  [ABILITY_CONDITION_TYPES.IS_OWN_TURN]: "E seu turno",
  [ABILITY_CONDITION_TYPES.IS_OPPONENT_TURN]: "E turno do oponente",
  [ABILITY_CONDITION_TYPES.SUPPORT_IS_ACTIVE]: "Suporte esta ativo",
  [ABILITY_CONDITION_TYPES.DAMAGE_AMOUNT_GTE]: "Dano minimo",
  [ABILITY_CONDITION_TYPES.WOULD_BE_KNOCKED_OUT]: "Seria nocauteado",
  [ABILITY_CONDITION_TYPES.ONCE_PER_TURN]: "Uma vez por turno",
  [ABILITY_CONDITION_TYPES.SOURCE_META_VALUE_IN]: "Meta da fonte contem",
  [ABILITY_CONDITION_TYPES.TARGET_META_VALUE_IN]: "Meta do alvo contem",
};

export const CARD_META_AGES = {
  CRIANCA: "CRIANCA",
  JOVEM: "JOVEM",
  ADULTO: "ADULTO",
  VELHO: "VELHO",
};

export const CARD_META_AGE_LABELS = {
  [CARD_META_AGES.CRIANCA]: "Crianca",
  [CARD_META_AGES.JOVEM]: "Jovem",
  [CARD_META_AGES.ADULTO]: "Adulto",
  [CARD_META_AGES.VELHO]: "Velho",
};

export const COMMON_META_ELEMENTS = ["AGUA", "FOGO", "GELO", "TERRA", "VENTO", "RAIO", "LUZ", "SOMBRA"];
export const COMMON_META_WEAPONS = ["ESPADA", "VARINHA", "PISTOLA", "ARCO", "LANCA", "ESCUDO", "KUNAI", "BASTAO"];
export const COMMON_META_STYLES = ["LOGIA", "MAGIA", "TECNOLOGIA", "NINJUTSU", "TAIJUTSU", "ESPIRITUAL", "MARCIAL"];
export const CARD_META_KEYS = ["age", "elements", "weapon", "style", "tags"];

export const ACTIVE_CONDITION_TYPES = {
  POISON: "POISON",
  BURN: "BURN",
  PARALYSIS: "PARALYSIS",
  FREEZE: "FREEZE",
  CONFUSED: "CONFUSED",
  SLEEP: "SLEEP",
};

export const ACTIVE_CONDITION_LABELS = {
  [ACTIVE_CONDITION_TYPES.POISON]: "Veneno",
  [ACTIVE_CONDITION_TYPES.BURN]: "Queimadura",
  [ACTIVE_CONDITION_TYPES.PARALYSIS]: "Paralisia",
  [ACTIVE_CONDITION_TYPES.FREEZE]: "Congelado",
  [ACTIVE_CONDITION_TYPES.CONFUSED]: "Confuso",
  [ACTIVE_CONDITION_TYPES.SLEEP]: "Sono",
};

export const ABILITY_POSITION_VALUES = {
  ACTIVE: "ACTIVE",
  BENCH: "BENCH",
  DISCARD: "DISCARD",
  HAND: "HAND",
};

export const ABILITY_POSITION_LABELS = {
  [ABILITY_POSITION_VALUES.ACTIVE]: "Ativa",
  [ABILITY_POSITION_VALUES.BENCH]: "Banco",
  [ABILITY_POSITION_VALUES.DISCARD]: "Cemitério",
  [ABILITY_POSITION_VALUES.HAND]: "Mão",
};

export const ABILITY_POSITION_OPTIONS = Object.values(ABILITY_POSITION_VALUES)
  .map(value => ({ value, label: ABILITY_POSITION_LABELS[value] }))
  .sort((a, b) => a.label.localeCompare(b.label, "pt-BR", { sensitivity: "base" }));

export const effectTypeLabel = type => EFFECT_TYPE_LABELS[type] || labelFromValue(type);
export const targetLabel = target => TARGET_LABELS[target] || labelFromValue(target);
export const durationLabel = duration => DURATION_LABELS[duration] || labelFromValue(duration);
export const conditionLabel = condition => EFFECT_CONDITION_LABELS[condition || ""] || labelFromValue(condition);
export const abilityTriggerLabel = trigger => ABILITY_TRIGGER_LABELS[trigger] || labelFromValue(trigger);
export const abilityConditionLabel = type => ABILITY_CONDITION_LABELS[type] || labelFromValue(type);
export const abilityPositionLabel = value => ABILITY_POSITION_LABELS[value] || labelFromValue(value);

export const abilityConditionValueLabel = condition => {
  if (!condition) return "";
  const value = condition.value;
  if (condition.type === ABILITY_CONDITION_TYPES.SOURCE_POSITION || condition.type === ABILITY_CONDITION_TYPES.TARGET_POSITION) {
    const values = Array.isArray(value) ? value : [value];
    return values.filter(Boolean).map(abilityPositionLabel).join(", ");
  }
  if (condition.type === ABILITY_CONDITION_TYPES.SOURCE_META_VALUE_IN || condition.type === ABILITY_CONDITION_TYPES.TARGET_META_VALUE_IN) {
    const values = Array.isArray(value?.values) ? value.values.join(", ") : "";
    return value?.key ? `${value.key}: ${values}` : values;
  }
  return Array.isArray(value) ? value.join(", ") : value;
};

const optionsFromValues = (values, labeler) => values
  .map(value => ({ value, label: labeler(value) }))
  .sort((a, b) => a.label.localeCompare(b.label, "pt-BR", { sensitivity: "base" }));

export const CANONICAL_TARGETS = new Set([
  TARGETS.SELF,
  TARGETS.SELF_ACTIVE,
  TARGETS.SELF_BENCH,
  TARGETS.SELF_BENCH_RANDOM,
  TARGETS.SELF_BENCH_CHOOSE,
  TARGETS.SELF_BENCH_BY_NATURE,
  TARGETS.SELF_BENCH_BY_NAME,
  TARGETS.ANY_SELF_CARD,
  TARGETS.ALL_SELF_CARDS,
  TARGETS.ALL_SELF_BENCH,
  TARGETS.EQUIPPED_CARD,
  TARGETS.DAMAGE_SOURCE,
  TARGETS.DAMAGE_TARGET,
  TARGETS.OPPONENT_ACTIVE,
  TARGETS.OPPONENT_BENCH,
  TARGETS.OPPONENT_BENCH_RANDOM,
  TARGETS.OPPONENT_BENCH_CHOOSE,
  TARGETS.ANY_BENCH_CHOOSE,
  TARGETS.ANY_OPPONENT_CARD,
  TARGETS.ALL_OPPONENT_CARDS,
  TARGETS.ALL_OPPONENT_BENCH,
  TARGETS.PREVIOUSLY_DAMAGED_OPPONENT,
]);

export const TARGET_ALIASES = {
  [TARGETS.ACTIVE]: TARGETS.SELF_ACTIVE,
  [TARGETS.BENCH]: TARGETS.SELF_BENCH,
  [TARGETS.ANY]: TARGETS.ANY_OPPONENT_CARD,
  [TARGETS.ALL_ENEMY]: TARGETS.ALL_OPPONENT_CARDS,
  [TARGETS.ALL_ALLY]: TARGETS.ALL_SELF_CARDS,
};

export const MANUAL_BENCH_TARGETS = new Set([
  TARGETS.SELF_BENCH_CHOOSE,
  TARGETS.OPPONENT_BENCH_CHOOSE,
  TARGETS.ANY_BENCH_CHOOSE,
]);

export const isManualTarget = target => MANUAL_BENCH_TARGETS.has(target);

export const VISIBLE_ABILITY_TRIGGERS = new Set([
  ABILITY_TRIGGERS.ON_ATTACK,
  ABILITY_TRIGGERS.BEFORE_ALLY_ACTIVE_TAKES_DAMAGE,
  ABILITY_TRIGGERS.ALLY_ACTIVE_WOULD_BE_KNOCKED_OUT,
  ABILITY_TRIGGERS.ON_DAMAGE_TAKEN,
  ABILITY_TRIGGERS.ON_TURN_START,
  ABILITY_TRIGGERS.ON_TURN_END,
  ABILITY_TRIGGERS.ON_ENERGY_ATTACHED,
  ABILITY_TRIGGERS.ON_KNOCKOUT,
  ABILITY_TRIGGERS.BEFORE_KNOCKOUT,
  ABILITY_TRIGGERS.AFTER_KNOCKOUT,
  ABILITY_TRIGGERS.PASSIVE_ACTIVE,
  ABILITY_TRIGGERS.PASSIVE_BENCH,
  ABILITY_TRIGGERS.ON_RETREAT,
  ABILITY_TRIGGERS.ON_EVOLVE,
  ABILITY_TRIGGERS.ON_ENTER_ACTIVE,
  ABILITY_TRIGGERS.ON_SUPPORT_PLAYED,
]);

export const ABILITY_TRIGGER_ALIASES = {
  [ABILITY_TRIGGERS.ON_RECEIVE_DAMAGE]: ABILITY_TRIGGERS.ON_DAMAGE_TAKEN,
  [ABILITY_TRIGGERS.ON_KO]: ABILITY_TRIGGERS.BEFORE_KNOCKOUT,
  [ABILITY_TRIGGERS.ON_OPPONENT_KO]: ABILITY_TRIGGERS.ON_KNOCKOUT,
  [ABILITY_TRIGGERS.INTERRUPT]: ABILITY_TRIGGERS.BEFORE_ALLY_ACTIVE_TAKES_DAMAGE,
  [ABILITY_TRIGGERS.BEFORE_DAMAGE_TAKEN]: ABILITY_TRIGGERS.BEFORE_ALLY_ACTIVE_TAKES_DAMAGE,
};

export const CANONICAL_ABILITY_CONDITION_TYPES = new Set([
  ABILITY_CONDITION_TYPES.SOURCE_POSITION,
  ABILITY_CONDITION_TYPES.TARGET_POSITION,
  ABILITY_CONDITION_TYPES.TARGET_NATURE_IN,
  ABILITY_CONDITION_TYPES.SOURCE_NATURE_IN,
  ABILITY_CONDITION_TYPES.TARGET_CARD_TYPE_IN,
  ABILITY_CONDITION_TYPES.SOURCE_CARD_TYPE_IN,
  ABILITY_CONDITION_TYPES.TARGET_IS_DAMAGED,
  ABILITY_CONDITION_TYPES.SELF_HAS_ENERGY_TYPE,
  ABILITY_CONDITION_TYPES.SELF_ENERGY_COUNT_GTE,
  ABILITY_CONDITION_TYPES.TARGET_ENERGY_COUNT_GTE,
  ABILITY_CONDITION_TYPES.BENCH_HAS_CARD_NAME,
  ABILITY_CONDITION_TYPES.TARGET_IS_CARD_NAME,
  ABILITY_CONDITION_TYPES.BENCH_HAS_NATURE,
  ABILITY_CONDITION_TYPES.BENCH_COUNT_BY_NATURE,
  ABILITY_CONDITION_TYPES.HAS_EQUIPMENT,
  ABILITY_CONDITION_TYPES.TARGET_HAS_EQUIPMENT,
  ABILITY_CONDITION_TYPES.SOURCE_HAS_EQUIPMENT,
  ABILITY_CONDITION_TYPES.SOURCE_HAS_NO_EQUIPMENT,
  ABILITY_CONDITION_TYPES.TARGET_HAS_ENERGY,
  ABILITY_CONDITION_TYPES.TARGET_HAS_TAG,
  ABILITY_CONDITION_TYPES.SOURCE_META_VALUE_IN,
  ABILITY_CONDITION_TYPES.TARGET_META_VALUE_IN,
  ABILITY_CONDITION_TYPES.SOURCE_HAS_CONDITION,
  ABILITY_CONDITION_TYPES.TARGET_HAS_CONDITION,
  ABILITY_CONDITION_TYPES.DICE_RESULT_GTE,
  ABILITY_CONDITION_TYPES.DICE_RESULT_LTE,
  ABILITY_CONDITION_TYPES.COIN_IS_HEADS,
  ABILITY_CONDITION_TYPES.COIN_IS_TAILS,
  ABILITY_CONDITION_TYPES.IS_OWN_TURN,
  ABILITY_CONDITION_TYPES.IS_OPPONENT_TURN,
  ABILITY_CONDITION_TYPES.DAMAGE_AMOUNT_GTE,
  ABILITY_CONDITION_TYPES.WOULD_BE_KNOCKED_OUT,
  ABILITY_CONDITION_TYPES.ONCE_PER_TURN,
]);

export const CANONICAL_DURATIONS = new Set([
  DURATIONS.INSTANT,
  DURATIONS.NEXT_DAMAGE,
  DURATIONS.THIS_TURN,
  DURATIONS.NEXT_TURN,
  DURATIONS.UNTIL_TURN_END,
  DURATIONS.UNTIL_CONDITION_CLEARED,
  DURATIONS.UNTIL_LEAVES_ACTIVE,
  DURATIONS.UNTIL_RETURNS_TO_BENCH,
  DURATIONS.UNTIL_KNOCKED_OUT,
  DURATIONS.PERMANENT_WHILE_IN_PLAY,
]);

export const EFFECT_TYPE_OPTIONS = optionsFromValues(
  Object.values(EFFECT_TYPES).filter(value => CANONICAL_EFFECT_TYPES.has(value)),
  effectTypeLabel
);

export const TARGET_OPTIONS = optionsFromValues(
  Object.values(TARGETS).filter(value => CANONICAL_TARGETS.has(value)),
  targetLabel
);

export const DURATION_OPTIONS = optionsFromValues(
  Object.values(DURATIONS).filter(value => CANONICAL_DURATIONS.has(value)),
  durationLabel
);

export const ABILITY_TRIGGER_OPTIONS = optionsFromValues(
  Object.values(ABILITY_TRIGGERS).filter(value => VISIBLE_ABILITY_TRIGGERS.has(value)),
  abilityTriggerLabel
);

export const ABILITY_CONDITION_OPTIONS = optionsFromValues(
  Object.values(ABILITY_CONDITION_TYPES).filter(value => CANONICAL_ABILITY_CONDITION_TYPES.has(value)),
  abilityConditionLabel
);

export const TARGET_FILTER_TYPES = new Set([
  ABILITY_CONDITION_TYPES.TARGET_NATURE_IN,
  ABILITY_CONDITION_TYPES.TARGET_CARD_TYPE_IN,
  ABILITY_CONDITION_TYPES.TARGET_HAS_TAG,
  ABILITY_CONDITION_TYPES.TARGET_META_VALUE_IN,
  ABILITY_CONDITION_TYPES.TARGET_HAS_EQUIPMENT,
  ABILITY_CONDITION_TYPES.TARGET_IS_DAMAGED,
  ABILITY_CONDITION_TYPES.TARGET_HAS_ENERGY,
  ABILITY_CONDITION_TYPES.TARGET_ENERGY_COUNT_GTE,
  ABILITY_CONDITION_TYPES.TARGET_HAS_CONDITION,
  ABILITY_CONDITION_TYPES.TARGET_IS_CARD_NAME,
]);

export const TARGET_FILTER_OPTIONS = optionsFromValues(
  Object.values(ABILITY_CONDITION_TYPES).filter(value => TARGET_FILTER_TYPES.has(value)),
  abilityConditionLabel
);

export const EQUIPMENT_EFFECT_TYPE_OPTIONS = Object.values(EFFECT_TYPES)
  .filter(value => CANONICAL_EFFECT_TYPES.has(value))
  .map(value => ({ value, label: effectTypeLabel(value) }))
  .sort((a, b) => a.label.localeCompare(b.label, "pt-BR", { sensitivity: "base" }));

const normalizeStringList = value => {
  if (Array.isArray(value)) return value.map(item => String(item).trim()).filter(Boolean);
  if (typeof value === "string") return value.split(",").map(item => item.trim()).filter(Boolean);
  return [];
};

const normalizeTargetValue = target => TARGET_ALIASES[target] || target || "";

const statusEffectFromConditionType = conditionType => {
  const normalized = String(conditionType || "").trim().toUpperCase();
  const map = {
    POISON: EFFECT_TYPES.POISON,
    BURN: EFFECT_TYPES.BURN,
    FREEZE: EFFECT_TYPES.FREEZE,
    PARALYSIS: EFFECT_TYPES.PARALYZE,
    PARALYZE: EFFECT_TYPES.PARALYZE,
    CONFUSED: EFFECT_TYPES.CONFUSE,
    CONFUSE: EFFECT_TYPES.CONFUSE,
    SLEEP: EFFECT_TYPES.PREVENT_ATTACK,
    PREVENT_ATTACK: EFFECT_TYPES.PREVENT_ATTACK,
    PREVENT_RETREAT: EFFECT_TYPES.PREVENT_RETREAT,
    BLOCK_RETREAT: EFFECT_TYPES.BLOCK_RETREAT,
  };
  return map[normalized] || EFFECT_TYPES.PREVENT_ATTACK;
};

const LEGACY_CONDITION_EFFECT_TYPES = new Set([
  EFFECT_TYPES.IF_TARGET_NATURE,
  EFFECT_TYPES.IF_TARGET_TAG,
  EFFECT_TYPES.IF_SELF_HAS_ENERGY_COUNT,
  EFFECT_TYPES.IF_BENCH_HAS_CARD,
  EFFECT_TYPES.IF_BENCH_COUNT_BY_NATURE,
  EFFECT_TYPES.IF_HAS_TOOL_ATTACHED,
  EFFECT_TYPES.IF_CARD_WAS_ATTACKED,
  EFFECT_TYPES.IF_CARD_KNOCKED_OUT,
  EFFECT_TYPES.ON_ATTACK,
  EFFECT_TYPES.ON_DAMAGE_TAKEN,
  EFFECT_TYPES.ON_ENERGY_ATTACHED,
  EFFECT_TYPES.ON_KNOCKOUT,
  EFFECT_TYPES.ON_TURN_START,
  EFFECT_TYPES.ON_TURN_END,
]);

export const normalizeEffectType = effect => {
  if (!effect?.type) return null;
  if (LEGACY_CONDITION_EFFECT_TYPES.has(effect.type)) return null;

  let type = EFFECT_TYPE_ALIASES[effect.type] || effect.type;
  let target = normalizeTargetValue(effect.target);
  let conditionType = effect.condition_type || effect.conditionType || "";

  if (effect.type === EFFECT_TYPES.APPLY_CONDITION) {
    type = statusEffectFromConditionType(conditionType);
  } else if (effect.type === EFFECT_TYPES.BLOCK_ACTION) {
    type = String(conditionType || "").toUpperCase().includes("RETREAT")
      ? EFFECT_TYPES.PREVENT_RETREAT
      : EFFECT_TYPES.PREVENT_ATTACK;
  } else if (effect.type === EFFECT_TYPES.IMMUNITY) {
    type = effect.applies_to === "NEGATIVE_EFFECTS"
      ? EFFECT_TYPES.IMMUNE_TO_NEGATIVE_EFFECTS
      : EFFECT_TYPES.IMMUNE_TO_DAMAGE_TYPE;
  } else if (effect.type === EFFECT_TYPES.SWITCH_ACTIVE) {
    type = String(effect.target || "").startsWith("OPPONENT")
      ? EFFECT_TYPES.SWITCH_OPPONENT_ACTIVE
      : EFFECT_TYPES.SWITCH_OWN_ACTIVE;
  } else if (effect.type === EFFECT_TYPES.IF_DICE_GREATER_THAN) {
    type = EFFECT_TYPES.DICE_ROLL;
  } else if (effect.type === EFFECT_TYPES.IF_DICE_LESS_THAN) {
    type = EFFECT_TYPES.DICE_ROLL;
  }

  if (effect.type === EFFECT_TYPES.ADD_ENERGY_TO_ACTIVE) target = TARGETS.SELF_ACTIVE;
  if (effect.type === EFFECT_TYPES.ADD_ENERGY_TO_BENCH) target = TARGETS.SELF_BENCH;
  if (effect.type === EFFECT_TYPES.HEAL_SELF || effect.type === EFFECT_TYPES.HEAL_ACTIVE) target = TARGETS.SELF_ACTIVE;
  if ([EFFECT_TYPES.HEAL_BENCH, EFFECT_TYPES.HEAL_BENCH_CARD, EFFECT_TYPES.HEAL_BENCH_GROUP].includes(effect.type)) {
    target = TARGETS.SELF_BENCH;
  }
  if ([EFFECT_TYPES.HEAL_ANY_SELF_CARD, EFFECT_TYPES.HEAL_ANY_ALLY].includes(effect.type)) {
    target = TARGETS.ANY_SELF_CARD;
  }
  if (effect.type === EFFECT_TYPES.HEAL_EQUIPPED_CARD) target = TARGETS.EQUIPPED_CARD;

  if (!CANONICAL_EFFECT_TYPES.has(type)) return null;
  return { type, target, condition_type: conditionType };
};

const normalizeAbilityTrigger = trigger => ABILITY_TRIGGER_ALIASES[trigger] || trigger;

const normalizeConditionValue = value => {
  if (Array.isArray(value)) return value.map(item => String(item).trim()).filter(Boolean);
  if (typeof value === "string" && value.includes(",")) {
    return value.split(",").map(item => item.trim()).filter(Boolean);
  }
  return value ?? "";
};

const normalizeAbilityCondition = condition => {
  if (!condition?.type) return null;
  const type = condition.type;
  if (type === ABILITY_CONDITION_TYPES.SOURCE_IS_ACTIVE) {
    return { ...condition, type: ABILITY_CONDITION_TYPES.SOURCE_POSITION, value: ABILITY_POSITION_VALUES.ACTIVE };
  }
  if (type === ABILITY_CONDITION_TYPES.SOURCE_IS_ON_BENCH) {
    return { ...condition, type: ABILITY_CONDITION_TYPES.SOURCE_POSITION, value: ABILITY_POSITION_VALUES.BENCH };
  }
  if (type === ABILITY_CONDITION_TYPES.TARGET_IS_ACTIVE) {
    return { ...condition, type: ABILITY_CONDITION_TYPES.TARGET_POSITION, value: ABILITY_POSITION_VALUES.ACTIVE };
  }
  if (type === ABILITY_CONDITION_TYPES.TARGET_IS_ON_BENCH) {
    return { ...condition, type: ABILITY_CONDITION_TYPES.TARGET_POSITION, value: ABILITY_POSITION_VALUES.BENCH };
  }
  if (type === ABILITY_CONDITION_TYPES.SOURCE_META_IN) {
    return { ...condition, type: ABILITY_CONDITION_TYPES.SOURCE_META_VALUE_IN };
  }
  if (type === ABILITY_CONDITION_TYPES.TARGET_META_IN) {
    return { ...condition, type: ABILITY_CONDITION_TYPES.TARGET_META_VALUE_IN };
  }
  if (type === ABILITY_CONDITION_TYPES.TARGET_USES_ELEMENT) {
    return {
      ...condition,
      type: ABILITY_CONDITION_TYPES.TARGET_META_VALUE_IN,
      value: {
        key: "elements",
        values: normalizeStringList(condition.value),
      },
    };
  }
  return condition;
};

export const normalizeTargetFilters = filters => (
  Array.isArray(filters)
    ? filters
        .map(normalizeAbilityCondition)
        .filter(Boolean)
        .filter(filter => filter?.type && TARGET_FILTER_TYPES.has(filter.type))
        .map(filter => ({
          type: filter.type,
          value: normalizeConditionValue(filter.value),
          negate: Boolean(filter.negate),
        }))
    : []
);

const valuesMatchAny = (value, candidates) => {
  const expected = Array.isArray(value)
    ? value
    : String(value || "").split(",").map(item => item.trim()).filter(Boolean);
  return expected.some(item => candidates.includes(item));
};

const cardTagsUpper = card => [
  ...(card?.tags || []),
  ...(card?.meta?.tags || []),
].map(tag => String(tag).trim().toUpperCase()).filter(Boolean);

const normalizeStatusFilterValue = value => {
  const normalized = String(value || "").trim().toUpperCase();
  const map = {
    POISON: "poison",
    BURN: "burn",
    PARALYSIS: "paralyze",
    PARALYZE: "paralyze",
    FREEZE: "freeze",
    CONFUSED: "confuse",
    CONFUSE: "confuse",
    SLEEP: "sleep",
    PREVENT_ATTACK: "prevent_attack",
    PREVENT_RETREAT: "prevent_retreat",
    BLOCK_RETREAT: "block_retreat",
  };
  return map[normalized] || normalized.toLowerCase();
};

export const targetFilterMatchesCard = (card, filter) => {
  if (!card || !filter?.type) return false;
  const result = (() => {
    switch (filter.type) {
      case ABILITY_CONDITION_TYPES.TARGET_NATURE_IN:
        return valuesMatchAny(filter.value, card.natures || []);
      case ABILITY_CONDITION_TYPES.TARGET_CARD_TYPE_IN:
        return valuesMatchAny(filter.value, [card.card_type].filter(Boolean));
      case ABILITY_CONDITION_TYPES.TARGET_HAS_TAG: {
        const expected = Array.isArray(filter.value) ? filter.value : String(filter.value || "").split(",");
        const normalized = expected.map(item => String(item).trim().toUpperCase()).filter(Boolean);
        return normalized.length > 0 && normalized.some(tag => cardTagsUpper(card).includes(tag));
      }
      case ABILITY_CONDITION_TYPES.TARGET_META_VALUE_IN: {
        const key = filter.value?.key || filter.value?.meta_key;
        const expected = Array.isArray(filter.value?.values)
          ? filter.value.values
          : String(filter.value?.values || filter.value?.value || "").split(",");
        const normalized = expected.map(item => String(item).trim().toUpperCase()).filter(Boolean);
        const current = card?.meta?.[key];
        const values = Array.isArray(current) ? current : [current];
        return Boolean(key) && normalized.length > 0 && values
          .map(item => String(item).trim().toUpperCase())
          .some(item => normalized.includes(item));
      }
      case ABILITY_CONDITION_TYPES.TARGET_HAS_EQUIPMENT:
        return (card.equipments || []).length > 0;
      case ABILITY_CONDITION_TYPES.TARGET_IS_DAMAGED:
        return (parseInt(card.hp_remaining, 10) || 0) < (parseInt(card.hp, 10) || 0);
      case ABILITY_CONDITION_TYPES.TARGET_HAS_ENERGY:
        return (card.attached_energy || []).length > 0;
      case ABILITY_CONDITION_TYPES.TARGET_ENERGY_COUNT_GTE:
        return (card.attached_energy || []).length >= (parseInt(filter.value, 10) || 0);
      case ABILITY_CONDITION_TYPES.TARGET_HAS_CONDITION:
        return (card.status_effects || []).some(status => (
          !filter.value || filter.value === "ANY" || normalizeStatusFilterValue(filter.value) === status
        ));
      case ABILITY_CONDITION_TYPES.TARGET_IS_CARD_NAME:
        return card.name === filter.value;
      default:
        return false;
    }
  })();
  return filter.negate ? !result : result;
};

export const targetFiltersMatchCard = (card, filters = []) => (
  normalizeTargetFilters(filters).every(filter => targetFilterMatchesCard(card, filter))
);

export const normalizeCardMeta = meta => ({
  age: String(meta?.age || "").trim(),
  elements: normalizeStringList(meta?.elements),
  weapon: String(meta?.weapon || "").trim(),
  style: String(meta?.style || "").trim(),
  tags: normalizeStringList(meta?.tags),
});

export const advancedEffectExtraFields = {
  hits: 0,
  count: 0,
  random_targets_count: 0,
  split_mode: "",
  allow_manual_target: false,
  natures: [],
  tags: [],
  per_count: false,
  per_energy_amount: 0,
  energy_owner: "",
  discard_amount: 0,
  random: false,
  dice_threshold: 0,
  comparison: "",
  success_effects: [],
  fail_effects: [],
  roll_count_source: "",
  success_amount: 0,
  damage_type: "",
  applies_to: "",
  absorb_hp: false,
  absorb_damage: false,
  absorb_energy: false,
  keep_negative_effects: false,
  temporary_hp: 0,
  filter_type: "",
  card_type: "",
  stack_key: "",
  reset_on_miss: false,
  discard_self: false,
  applies_to_tag: "",
  applies_to_nature: "",
  meta_key: "",
  meta_value: "",
  priority: 10,
  value_formula: "",
  dice_type: "",
  dice_condition: "",
  condition_type: "",
  description: "",
  formula: "",
  chain_trigger: "",
  chain_target: "",
  target_filters: [],
};

export const normalizeEffects = effects => (
  Array.isArray(effects)
    ? effects
        .filter(effect => effect?.type)
        .map(effect => {
          const normalizedType = normalizeEffectType(effect);
          if (!normalizedType) return null;
          return {
            ...advancedEffectExtraFields,
            type: normalizedType.type,
            target: normalizedType.target,
            duration: CANONICAL_DURATIONS.has(effect.duration) ? effect.duration : DURATIONS.INSTANT,
            amount: Math.max(0, parseInt(effect.amount, 10) || 0),
            attribute: effect.attribute || "",
            energy_type: effect.energy_type || "",
            nature: effect.nature || "",
            natures: normalizeStringList(effect.natures),
            card_name: effect.card_name || "",
            cardName: effect.cardName || "",
            tag: effect.tag || "",
            tags: normalizeStringList(effect.tags),
            condition: effect.condition || "",
            hits: Math.max(0, parseInt(effect.hits, 10) || 0),
            count: Math.max(0, parseInt(effect.count, 10) || 0),
            random_targets_count: Math.max(0, parseInt(effect.random_targets_count, 10) || 0),
            split_mode: effect.split_mode || "",
            allow_manual_target: isManualTarget(normalizedType.target) || Boolean(effect.allow_manual_target),
            per_count: Boolean(effect.per_count),
            per_energy_amount: Math.max(0, parseInt(effect.per_energy_amount, 10) || 0),
            energy_owner: effect.energy_owner || "",
            discard_amount: Math.max(0, parseInt(effect.discard_amount, 10) || 0),
            random: Boolean(effect.random),
            dice_threshold: Math.max(0, parseInt(effect.dice_threshold, 10) || 0),
            comparison: effect.comparison || (effect.type === EFFECT_TYPES.IF_DICE_LESS_THAN ? "LT" : ""),
            success_effects: normalizeEffects(effect.success_effects),
            fail_effects: normalizeEffects(effect.fail_effects),
            roll_count_source: effect.roll_count_source || "",
            success_amount: Math.max(0, parseInt(effect.success_amount, 10) || 0),
            damage_type: effect.damage_type || "",
            applies_to: effect.applies_to || "",
            absorb_hp: Boolean(effect.absorb_hp),
            absorb_damage: Boolean(effect.absorb_damage),
            absorb_energy: Boolean(effect.absorb_energy),
            keep_negative_effects: Boolean(effect.keep_negative_effects),
            temporary_hp: Math.max(0, parseInt(effect.temporary_hp, 10) || 0),
            filter_type: effect.filter_type || "",
            card_type: effect.card_type || "",
            stack_key: effect.stack_key || "",
            reset_on_miss: Boolean(effect.reset_on_miss),
            discard_self: Boolean(effect.discard_self || effect.discardSelf),
            applies_to_tag: effect.applies_to_tag || "",
            applies_to_nature: effect.applies_to_nature || "",
            meta_key: effect.meta_key || "",
            meta_value: effect.meta_value || "",
            priority: Math.max(0, parseInt(effect.priority, 10) || 10),
            value_formula: effect.value_formula || effect.valueFormula || "",
            formula: effect.formula || effect.value_formula || effect.valueFormula || "",
            dice_type: effect.dice_type || effect.diceType || "",
            dice_condition: effect.dice_condition || effect.diceCondition || "",
            condition_type: normalizedType.condition_type,
            description: effect.description || "",
            chain_trigger: normalizeAbilityTrigger(effect.chain_trigger || effect.chainTrigger || ""),
            chain_target: effect.chain_target || effect.chainTarget || "",
            target_filters: normalizeTargetFilters(effect.target_filters),
          };
        })
        .filter(Boolean)
    : []
);

export const shouldApplyEquipmentPassiveEffect = (effect, trigger) => {
  if (!effect?.type || !trigger) return false;
  const condition = effect.condition || EFFECT_CONDITIONS.ALWAYS;
  if (condition === trigger) return true;
  return (
    trigger === EFFECT_CONDITIONS.ON_EQUIP &&
    condition === EFFECT_CONDITIONS.ALWAYS &&
    EQUIPMENT_ON_EQUIP_EFFECT_TYPES.has(effect.type)
  );
};

export const normalizeEquipmentPassiveEffects = effects => (
  normalizeEffects(effects).map(effect => ({
    ...effect,
    condition: (
      (effect.condition || EFFECT_CONDITIONS.ALWAYS) === EFFECT_CONDITIONS.ALWAYS &&
      EQUIPMENT_ON_EQUIP_EFFECT_TYPES.has(effect.type)
    )
      ? EFFECT_CONDITIONS.ON_EQUIP
      : effect.condition,
  }))
);

export const effectSummary = effect => {
  const type = effectTypeLabel(effect.type);
  const target = targetLabel(effect.target);
  const duration = effect.duration && effect.duration !== DURATIONS.INSTANT ? ` (${durationLabel(effect.duration)})` : "";
  const condition = effect.condition ? ` | ${conditionLabel(effect.condition)}` : "";
  const amount = effect.amount ? ` ${effect.amount}` : "";
  const details = [
    effect.nature,
    effect.energy_type,
    effect.attribute,
    effect.card_name,
    effect.tag,
    Array.isArray(effect.natures) ? effect.natures.join(", ") : "",
    Array.isArray(effect.tags) ? effect.tags.join(", ") : "",
    effect.card_type,
    effect.meta_key && effect.meta_value ? `${effect.meta_key}: ${effect.meta_value}` : "",
    effect.condition_type ? ACTIVE_CONDITION_LABELS[effect.condition_type] || effect.condition_type : "",
    effect.dice_type,
    effect.value_formula,
    effect.description,
  ].filter(Boolean);
  const extra = details.length ? ` | ${details.join(" / ")}` : "";
  const targetFilters = normalizeTargetFilters(effect.target_filters);
  const filters = targetFilters.length === 1
    ? ` | Filtro: ${abilityConditionLabel(targetFilters[0].type)}`
    : targetFilters.length > 1
      ? ` | Filtros: ${targetFilters.length}`
      : "";
  return `${type}${amount} - ${target}${duration}${condition}${extra}${filters}`;
};

export const normalizeAbilityConditions = conditions => (
  Array.isArray(conditions)
    ? conditions
        .filter(condition => condition?.type)
        .map(normalizeAbilityCondition)
        .filter(Boolean)
        .map(condition => ({
          type: condition.type,
          value: normalizeConditionValue(condition.value),
          negate: Boolean(condition.negate),
        }))
    : []
);

export const normalizeAbilityRules = rules => (
  Array.isArray(rules)
    ? rules
        .filter(rule => rule?.trigger)
        .map(rule => ({
          id: rule.id || "",
          name: rule.name || "",
          source: rule.source || "",
          trigger: normalizeAbilityTrigger(rule.trigger),
          conditions: normalizeAbilityConditions(rule.conditions),
          effects: normalizeEffects(rule.effects),
          duration: CANONICAL_DURATIONS.has(rule.duration) ? rule.duration : DURATIONS.INSTANT,
          chainTrigger: normalizeAbilityTrigger(rule.chainTrigger || rule.chain_trigger || ""),
          chainTarget: rule.chainTarget || rule.chain_target || "",
          priority: Math.max(0, parseInt(rule.priority, 10) || 10),
          once_per_turn: Boolean(rule.once_per_turn || rule.oncePerTurn),
          interrupt: Boolean(rule.interrupt),
        }))
        .filter(rule => rule.effects.length > 0)
    : []
);

export const ruleSummary = rule => {
  const effects = normalizeEffects(rule.effects).map(effectSummary).join(" + ");
  const conditions = normalizeAbilityConditions(rule.conditions)
    .map(condition => {
      const valueLabel = abilityConditionValueLabel(condition);
      return `${abilityConditionLabel(condition.type)}${valueLabel ? `: ${valueLabel}` : ""}`;
    })
    .join(" | ");
  return `${abilityTriggerLabel(rule.trigger)}${conditions ? ` (${conditions})` : ""}: ${effects}`;
};
